// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BootstrapListerExpansion allows custom methods to be added to
// BootstrapLister.
type BootstrapListerExpansion interface{}

// BootstrapNamespaceListerExpansion allows custom methods to be added to
// BootstrapNamespaceLister.
type BootstrapNamespaceListerExpansion interface{}

// ComponentListerExpansion allows custom methods to be added to
// ComponentLister.
type ComponentListerExpansion interface{}

// ComponentNamespaceListerExpansion allows custom methods to be added to
// ComponentNamespaceLister.
type ComponentNamespaceListerExpansion interface{}

// ComponentVersionListerExpansion allows custom methods to be added to
// ComponentVersionLister.
type ComponentVersionListerExpansion interface{}

// ComponentVersionNamespaceListerExpansion allows custom methods to be added to
// ComponentVersionNamespaceLister.
type ComponentVersionNamespaceListerExpansion interface{}

// ProfileListerExpansion allows custom methods to be added to
// ProfileLister.
type ProfileListerExpansion interface{}

// ProfileNamespaceListerExpansion allows custom methods to be added to
// ProfileNamespaceLister.
type ProfileNamespaceListerExpansion interface{}

// ReleaseListerExpansion allows custom methods to be added to
// ReleaseLister.
type ReleaseListerExpansion interface{}

// ReleaseNamespaceListerExpansion allows custom methods to be added to
// ReleaseNamespaceLister.
type ReleaseNamespaceListerExpansion interface{}

// RenderTaskListerExpansion allows custom methods to be added to
// RenderTaskLister.
type RenderTaskListerExpansion interface{}

// TargetListerExpansion allows custom methods to be added to
// TargetLister.
type TargetListerExpansion interface{}

// TargetNamespaceListerExpansion allows custom methods to be added to
// TargetNamespaceLister.
type TargetNamespaceListerExpansion interface{}
