// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HydratedTargetLister helps list HydratedTargets.
// All objects returned here must be treated as read-only.
type HydratedTargetLister interface {
	// List lists all HydratedTargets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.HydratedTarget, err error)
	// HydratedTargets returns an object that can list and get HydratedTargets.
	HydratedTargets(namespace string) HydratedTargetNamespaceLister
	HydratedTargetListerExpansion
}

// hydratedTargetLister implements the HydratedTargetLister interface.
type hydratedTargetLister struct {
	listers.ResourceIndexer[*solarv1alpha1.HydratedTarget]
}

// NewHydratedTargetLister returns a new HydratedTargetLister.
func NewHydratedTargetLister(indexer cache.Indexer) HydratedTargetLister {
	return &hydratedTargetLister{listers.New[*solarv1alpha1.HydratedTarget](indexer, solarv1alpha1.Resource("hydratedtarget"))}
}

// HydratedTargets returns an object that can list and get HydratedTargets.
func (s *hydratedTargetLister) HydratedTargets(namespace string) HydratedTargetNamespaceLister {
	return hydratedTargetNamespaceLister{listers.NewNamespaced[*solarv1alpha1.HydratedTarget](s.ResourceIndexer, namespace)}
}

// HydratedTargetNamespaceLister helps list and get HydratedTargets.
// All objects returned here must be treated as read-only.
type HydratedTargetNamespaceLister interface {
	// List lists all HydratedTargets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.HydratedTarget, err error)
	// Get retrieves the HydratedTarget from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*solarv1alpha1.HydratedTarget, error)
	HydratedTargetNamespaceListerExpansion
}

// hydratedTargetNamespaceLister implements the HydratedTargetNamespaceLister
// interface.
type hydratedTargetNamespaceLister struct {
	listers.ResourceIndexer[*solarv1alpha1.HydratedTarget]
}
