// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ReleaseLister helps list Releases.
// All objects returned here must be treated as read-only.
type ReleaseLister interface {
	// List lists all Releases in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.Release, err error)
	// Releases returns an object that can list and get Releases.
	Releases(namespace string) ReleaseNamespaceLister
	ReleaseListerExpansion
}

// releaseLister implements the ReleaseLister interface.
type releaseLister struct {
	listers.ResourceIndexer[*solarv1alpha1.Release]
}

// NewReleaseLister returns a new ReleaseLister.
func NewReleaseLister(indexer cache.Indexer) ReleaseLister {
	return &releaseLister{listers.New[*solarv1alpha1.Release](indexer, solarv1alpha1.Resource("release"))}
}

// Releases returns an object that can list and get Releases.
func (s *releaseLister) Releases(namespace string) ReleaseNamespaceLister {
	return releaseNamespaceLister{listers.NewNamespaced[*solarv1alpha1.Release](s.ResourceIndexer, namespace)}
}

// ReleaseNamespaceLister helps list and get Releases.
// All objects returned here must be treated as read-only.
type ReleaseNamespaceLister interface {
	// List lists all Releases in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.Release, err error)
	// Get retrieves the Release from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*solarv1alpha1.Release, error)
	ReleaseNamespaceListerExpansion
}

// releaseNamespaceLister implements the ReleaseNamespaceLister
// interface.
type releaseNamespaceLister struct {
	listers.ResourceIndexer[*solarv1alpha1.Release]
}
