// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ReleaseBindingLister helps list ReleaseBindings.
// All objects returned here must be treated as read-only.
type ReleaseBindingLister interface {
	// List lists all ReleaseBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.ReleaseBinding, err error)
	// ReleaseBindings returns an object that can list and get ReleaseBindings.
	ReleaseBindings(namespace string) ReleaseBindingNamespaceLister
	ReleaseBindingListerExpansion
}

// releaseBindingLister implements the ReleaseBindingLister interface.
type releaseBindingLister struct {
	listers.ResourceIndexer[*solarv1alpha1.ReleaseBinding]
}

// NewReleaseBindingLister returns a new ReleaseBindingLister.
func NewReleaseBindingLister(indexer cache.Indexer) ReleaseBindingLister {
	return &releaseBindingLister{listers.New[*solarv1alpha1.ReleaseBinding](indexer, solarv1alpha1.Resource("releasebinding"))}
}

// ReleaseBindings returns an object that can list and get ReleaseBindings.
func (s *releaseBindingLister) ReleaseBindings(namespace string) ReleaseBindingNamespaceLister {
	return releaseBindingNamespaceLister{listers.NewNamespaced[*solarv1alpha1.ReleaseBinding](s.ResourceIndexer, namespace)}
}

// ReleaseBindingNamespaceLister helps list and get ReleaseBindings.
// All objects returned here must be treated as read-only.
type ReleaseBindingNamespaceLister interface {
	// List lists all ReleaseBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.ReleaseBinding, err error)
	// Get retrieves the ReleaseBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*solarv1alpha1.ReleaseBinding, error)
	ReleaseBindingNamespaceListerExpansion
}

// releaseBindingNamespaceLister implements the ReleaseBindingNamespaceLister
// interface.
type releaseBindingNamespaceLister struct {
	listers.ResourceIndexer[*solarv1alpha1.ReleaseBinding]
}
