// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RenderBindingLister helps list RenderBindings.
// All objects returned here must be treated as read-only.
type RenderBindingLister interface {
	// List lists all RenderBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.RenderBinding, err error)
	// RenderBindings returns an object that can list and get RenderBindings.
	RenderBindings(namespace string) RenderBindingNamespaceLister
	RenderBindingListerExpansion
}

// renderBindingLister implements the RenderBindingLister interface.
type renderBindingLister struct {
	listers.ResourceIndexer[*solarv1alpha1.RenderBinding]
}

// NewRenderBindingLister returns a new RenderBindingLister.
func NewRenderBindingLister(indexer cache.Indexer) RenderBindingLister {
	return &renderBindingLister{listers.New[*solarv1alpha1.RenderBinding](indexer, solarv1alpha1.Resource("renderbinding"))}
}

// RenderBindings returns an object that can list and get RenderBindings.
func (s *renderBindingLister) RenderBindings(namespace string) RenderBindingNamespaceLister {
	return renderBindingNamespaceLister{listers.NewNamespaced[*solarv1alpha1.RenderBinding](s.ResourceIndexer, namespace)}
}

// RenderBindingNamespaceLister helps list and get RenderBindings.
// All objects returned here must be treated as read-only.
type RenderBindingNamespaceLister interface {
	// List lists all RenderBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.RenderBinding, err error)
	// Get retrieves the RenderBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*solarv1alpha1.RenderBinding, error)
	RenderBindingNamespaceListerExpansion
}

// renderBindingNamespaceLister implements the RenderBindingNamespaceLister
// interface.
type renderBindingNamespaceLister struct {
	listers.ResourceIndexer[*solarv1alpha1.RenderBinding]
}
