// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RenderArtifactLister helps list RenderArtifacts.
// All objects returned here must be treated as read-only.
type RenderArtifactLister interface {
	// List lists all RenderArtifacts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.RenderArtifact, err error)
	// RenderArtifacts returns an object that can list and get RenderArtifacts.
	RenderArtifacts(namespace string) RenderArtifactNamespaceLister
	RenderArtifactListerExpansion
}

// renderArtifactLister implements the RenderArtifactLister interface.
type renderArtifactLister struct {
	listers.ResourceIndexer[*solarv1alpha1.RenderArtifact]
}

// NewRenderArtifactLister returns a new RenderArtifactLister.
func NewRenderArtifactLister(indexer cache.Indexer) RenderArtifactLister {
	return &renderArtifactLister{listers.New[*solarv1alpha1.RenderArtifact](indexer, solarv1alpha1.Resource("renderartifact"))}
}

// RenderArtifacts returns an object that can list and get RenderArtifacts.
func (s *renderArtifactLister) RenderArtifacts(namespace string) RenderArtifactNamespaceLister {
	return renderArtifactNamespaceLister{listers.NewNamespaced[*solarv1alpha1.RenderArtifact](s.ResourceIndexer, namespace)}
}

// RenderArtifactNamespaceLister helps list and get RenderArtifacts.
// All objects returned here must be treated as read-only.
type RenderArtifactNamespaceLister interface {
	// List lists all RenderArtifacts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.RenderArtifact, err error)
	// Get retrieves the RenderArtifact from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*solarv1alpha1.RenderArtifact, error)
	RenderArtifactNamespaceListerExpansion
}

// renderArtifactNamespaceLister implements the RenderArtifactNamespaceLister
// interface.
type renderArtifactNamespaceLister struct {
	listers.ResourceIndexer[*solarv1alpha1.RenderArtifact]
}
