// Copyright BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TargetReportLister helps list TargetReports.
// All objects returned here must be treated as read-only.
type TargetReportLister interface {
	// List lists all TargetReports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.TargetReport, err error)
	// TargetReports returns an object that can list and get TargetReports.
	TargetReports(namespace string) TargetReportNamespaceLister
	TargetReportListerExpansion
}

// targetReportLister implements the TargetReportLister interface.
type targetReportLister struct {
	listers.ResourceIndexer[*solarv1alpha1.TargetReport]
}

// NewTargetReportLister returns a new TargetReportLister.
func NewTargetReportLister(indexer cache.Indexer) TargetReportLister {
	return &targetReportLister{listers.New[*solarv1alpha1.TargetReport](indexer, solarv1alpha1.Resource("targetreport"))}
}

// TargetReports returns an object that can list and get TargetReports.
func (s *targetReportLister) TargetReports(namespace string) TargetReportNamespaceLister {
	return targetReportNamespaceLister{listers.NewNamespaced[*solarv1alpha1.TargetReport](s.ResourceIndexer, namespace)}
}

// TargetReportNamespaceLister helps list and get TargetReports.
// All objects returned here must be treated as read-only.
type TargetReportNamespaceLister interface {
	// List lists all TargetReports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*solarv1alpha1.TargetReport, err error)
	// Get retrieves the TargetReport from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*solarv1alpha1.TargetReport, error)
	TargetReportNamespaceListerExpansion
}

// targetReportNamespaceLister implements the TargetReportNamespaceLister
// interface.
type targetReportNamespaceLister struct {
	listers.ResourceIndexer[*solarv1alpha1.TargetReport]
}
