apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: solar-catalog-transfer
spec:
  schedules:
    - "0 */6 * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  workflowSpec:
    workflowTemplateRef:
      clusterScope: true
      name: solar-catalog-transfer
    arguments:
      parameters:
        - name: dstRemoteURL
          value: "zot-deploy.zot.svc.cluster.local:443"
        - name: dstScheme
          value: "https"
        - name: srcSecret
          value: "true"
        - name: srcSecretName
          value: "src-reg-secret"
        - name: dstSecret
          value: "true"
        - name: dstSecretName
          value: "dst-reg-secret"
        - name: kubeconfigSecret
          value: "source-solar-kubeconfig"
        - name: scanSeverity
          value: "CRITICAL,HIGH"
        - name: scanExitCode
          value: "0"
  workflowMetadata:
    labels:
      solar.opendefense.cloud/cron: "solar-catalog-transfer"
