// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BootstrapStatusApplyConfiguration represents a declarative configuration of the BootstrapStatus type for use
// with apply.
//
// BootstrapStatus defines the observed state of a Bootstrap.
type BootstrapStatusApplyConfiguration struct {
	// Conditions represent the latest available observations of a Bootstrap's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// RenderTaskRef is a reference to the RenderTask responsible for this Bootstrap.
	RenderTaskRef *corev1.ObjectReference `json:"renderTaskRef,omitempty"`
}

// BootstrapStatusApplyConfiguration constructs a declarative configuration of the BootstrapStatus type for use with
// apply.
func BootstrapStatus() *BootstrapStatusApplyConfiguration {
	return &BootstrapStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BootstrapStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BootstrapStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithRenderTaskRef sets the RenderTaskRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenderTaskRef field is set to the value of the last call.
func (b *BootstrapStatusApplyConfiguration) WithRenderTaskRef(value corev1.ObjectReference) *BootstrapStatusApplyConfiguration {
	b.RenderTaskRef = &value
	return b
}
