// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// BootstrapInputApplyConfiguration represents a declarative configuration of the BootstrapInput type for use
// with apply.
//
// BootstrapInput defines the inputs to render a bootstrap.
type BootstrapInputApplyConfiguration struct {
	Releases map[string]ResourceAccessApplyConfiguration `json:"releases,omitempty"`
	// Userdata is additional data to be rendered into the bootstrap chart values.
	Userdata *runtime.RawExtension `json:"userdata,omitempty"`
}

// BootstrapInputApplyConfiguration constructs a declarative configuration of the BootstrapInput type for use with
// apply.
func BootstrapInput() *BootstrapInputApplyConfiguration {
	return &BootstrapInputApplyConfiguration{}
}

// WithReleases puts the entries into the Releases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Releases field,
// overwriting an existing map entries in Releases field with the same key.
func (b *BootstrapInputApplyConfiguration) WithReleases(entries map[string]ResourceAccessApplyConfiguration) *BootstrapInputApplyConfiguration {
	if b.Releases == nil && len(entries) > 0 {
		b.Releases = make(map[string]ResourceAccessApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Releases[k] = v
	}
	return b
}

// WithUserdata sets the Userdata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Userdata field is set to the value of the last call.
func (b *BootstrapInputApplyConfiguration) WithUserdata(value runtime.RawExtension) *BootstrapInputApplyConfiguration {
	b.Userdata = &value
	return b
}
