// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CatalogItemStatusApplyConfiguration represents a declarative configuration of the CatalogItemStatus type for use
// with apply.
type CatalogItemStatusApplyConfiguration struct {
	Phase              *solarv1alpha1.CatalogItemPhase      `json:"phase,omitempty"`
	Validation         *ValidationStatusApplyConfiguration  `json:"validation,omitempty"`
	Attestations       []AttestationApplyConfiguration      `json:"attestations,omitempty"`
	LastDiscoveredAt   *v1.Time                             `json:"lastDiscoveredAt,omitempty"`
	Conditions         []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	ObservedGeneration *int64                               `json:"observedGeneration,omitempty"`
}

// CatalogItemStatusApplyConfiguration constructs a declarative configuration of the CatalogItemStatus type for use with
// apply.
func CatalogItemStatus() *CatalogItemStatusApplyConfiguration {
	return &CatalogItemStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *CatalogItemStatusApplyConfiguration) WithPhase(value solarv1alpha1.CatalogItemPhase) *CatalogItemStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithValidation sets the Validation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Validation field is set to the value of the last call.
func (b *CatalogItemStatusApplyConfiguration) WithValidation(value *ValidationStatusApplyConfiguration) *CatalogItemStatusApplyConfiguration {
	b.Validation = value
	return b
}

// WithAttestations adds the given value to the Attestations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attestations field.
func (b *CatalogItemStatusApplyConfiguration) WithAttestations(values ...*AttestationApplyConfiguration) *CatalogItemStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAttestations")
		}
		b.Attestations = append(b.Attestations, *values[i])
	}
	return b
}

// WithLastDiscoveredAt sets the LastDiscoveredAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastDiscoveredAt field is set to the value of the last call.
func (b *CatalogItemStatusApplyConfiguration) WithLastDiscoveredAt(value v1.Time) *CatalogItemStatusApplyConfiguration {
	b.LastDiscoveredAt = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CatalogItemStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *CatalogItemStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *CatalogItemStatusApplyConfiguration) WithObservedGeneration(value int64) *CatalogItemStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
