// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CatalogItemSpecApplyConfiguration represents a declarative configuration of the CatalogItemSpec type for use
// with apply.
type CatalogItemSpecApplyConfiguration struct {
	Repository   *string                                    `json:"repository,omitempty"`
	Versions     []CatalogItemVersionSpecApplyConfiguration `json:"versions,omitempty"`
	Provider     *string                                    `json:"provider,omitempty"`
	CreationTime *v1.Time                                   `json:"creationTime,omitempty"`
}

// CatalogItemSpecApplyConfiguration constructs a declarative configuration of the CatalogItemSpec type for use with
// apply.
func CatalogItemSpec() *CatalogItemSpecApplyConfiguration {
	return &CatalogItemSpecApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *CatalogItemSpecApplyConfiguration) WithRepository(value string) *CatalogItemSpecApplyConfiguration {
	b.Repository = &value
	return b
}

// WithVersions adds the given value to the Versions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Versions field.
func (b *CatalogItemSpecApplyConfiguration) WithVersions(values ...*CatalogItemVersionSpecApplyConfiguration) *CatalogItemSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVersions")
		}
		b.Versions = append(b.Versions, *values[i])
	}
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *CatalogItemSpecApplyConfiguration) WithProvider(value string) *CatalogItemSpecApplyConfiguration {
	b.Provider = &value
	return b
}

// WithCreationTime sets the CreationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTime field is set to the value of the last call.
func (b *CatalogItemSpecApplyConfiguration) WithCreationTime(value v1.Time) *CatalogItemSpecApplyConfiguration {
	b.CreationTime = &value
	return b
}
