// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ChartConfigApplyConfiguration represents a declarative configuration of the ChartConfig type for use
// with apply.
type ChartConfigApplyConfiguration struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Version     *string `json:"version,omitempty"`
	AppVersion  *string `json:"appVersion,omitempty"`
}

// ChartConfigApplyConfiguration constructs a declarative configuration of the ChartConfig type for use with
// apply.
func ChartConfig() *ChartConfigApplyConfiguration {
	return &ChartConfigApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ChartConfigApplyConfiguration) WithName(value string) *ChartConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ChartConfigApplyConfiguration) WithDescription(value string) *ChartConfigApplyConfiguration {
	b.Description = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ChartConfigApplyConfiguration) WithVersion(value string) *ChartConfigApplyConfiguration {
	b.Version = &value
	return b
}

// WithAppVersion sets the AppVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppVersion field is set to the value of the last call.
func (b *ChartConfigApplyConfiguration) WithAppVersion(value string) *ChartConfigApplyConfiguration {
	b.AppVersion = &value
	return b
}
