// Copyright 2025 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ComponentDependencyApplyConfiguration represents a declarative configuration of the ComponentDependency type for use
// with apply.
type ComponentDependencyApplyConfiguration struct {
	ComponentName     *string `json:"componentName,omitempty"`
	VersionConstraint *string `json:"versionConstraint,omitempty"`
	Optional          *bool   `json:"optional,omitempty"`
}

// ComponentDependencyApplyConfiguration constructs a declarative configuration of the ComponentDependency type for use with
// apply.
func ComponentDependency() *ComponentDependencyApplyConfiguration {
	return &ComponentDependencyApplyConfiguration{}
}

// WithComponentName sets the ComponentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ComponentName field is set to the value of the last call.
func (b *ComponentDependencyApplyConfiguration) WithComponentName(value string) *ComponentDependencyApplyConfiguration {
	b.ComponentName = &value
	return b
}

// WithVersionConstraint sets the VersionConstraint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VersionConstraint field is set to the value of the last call.
func (b *ComponentDependencyApplyConfiguration) WithVersionConstraint(value string) *ComponentDependencyApplyConfiguration {
	b.VersionConstraint = &value
	return b
}

// WithOptional sets the Optional field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Optional field is set to the value of the last call.
func (b *ComponentDependencyApplyConfiguration) WithOptional(value bool) *ComponentDependencyApplyConfiguration {
	b.Optional = &value
	return b
}
