// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ComponentSpecApplyConfiguration represents a declarative configuration of the ComponentSpec type for use
// with apply.
//
// ComponentSpec defines the desired state of a Component.
// It contains metadata about an OCM component including its repository location,
// type classification, and the provider.
type ComponentSpecApplyConfiguration struct {
	// Scheme is the scheme to access the component.
	Scheme *string `json:"scheme,omitempty"`
	// Registry is the registry where the component is stored.
	Registry *string `json:"registry,omitempty"`
	// Repository is the repository where the component is stored.
	Repository *string `json:"repository,omitempty"`
}

// ComponentSpecApplyConfiguration constructs a declarative configuration of the ComponentSpec type for use with
// apply.
func ComponentSpec() *ComponentSpecApplyConfiguration {
	return &ComponentSpecApplyConfiguration{}
}

// WithScheme sets the Scheme field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheme field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithScheme(value string) *ComponentSpecApplyConfiguration {
	b.Scheme = &value
	return b
}

// WithRegistry sets the Registry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Registry field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithRegistry(value string) *ComponentSpecApplyConfiguration {
	b.Registry = &value
	return b
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithRepository(value string) *ComponentSpecApplyConfiguration {
	b.Repository = &value
	return b
}
