// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ComponentSpecApplyConfiguration represents a declarative configuration of the ComponentSpec type for use
// with apply.
type ComponentSpecApplyConfiguration struct {
	Repository *string `json:"repository,omitempty"`
	Type       *string `json:"type,omitempty"`
	Provider   *string `json:"provider,omitempty"`
}

// ComponentSpecApplyConfiguration constructs a declarative configuration of the ComponentSpec type for use with
// apply.
func ComponentSpec() *ComponentSpecApplyConfiguration {
	return &ComponentSpecApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithRepository(value string) *ComponentSpecApplyConfiguration {
	b.Repository = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithType(value string) *ComponentSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *ComponentSpecApplyConfiguration) WithProvider(value string) *ComponentSpecApplyConfiguration {
	b.Provider = &value
	return b
}
