// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ComponentSourceApplyConfiguration represents a declarative configuration of the ComponentSource type for use
// with apply.
type ComponentSourceApplyConfiguration struct {
	Registry *string `json:"registry,omitempty"`
	Path     *string `json:"path,omitempty"`
}

// ComponentSourceApplyConfiguration constructs a declarative configuration of the ComponentSource type for use with
// apply.
func ComponentSource() *ComponentSourceApplyConfiguration {
	return &ComponentSourceApplyConfiguration{}
}

// WithRegistry sets the Registry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Registry field is set to the value of the last call.
func (b *ComponentSourceApplyConfiguration) WithRegistry(value string) *ComponentSourceApplyConfiguration {
	b.Registry = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ComponentSourceApplyConfiguration) WithPath(value string) *ComponentSourceApplyConfiguration {
	b.Path = &value
	return b
}
