// Copyright 2025 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// DiscoverySpecApplyConfiguration represents a declarative configuration of the DiscoverySpec type for use
// with apply.
type DiscoverySpecApplyConfiguration struct {
	RemoteURL               *string                  `json:"remoteURL,omitempty"`
	DiscoverySecretRef      *v1.LocalObjectReference `json:"discoverySecretRef,omitempty"`
	ReleaseSecretRef        *v1.LocalObjectReference `json:"releaseSecretRef,omitempty"`
	Cron                    *CronApplyConfiguration  `json:"cron,omitempty"`
	DisableStartupDiscovery *bool                    `json:"disableStartupDiscovery,omitempty"`
}

// DiscoverySpecApplyConfiguration constructs a declarative configuration of the DiscoverySpec type for use with
// apply.
func DiscoverySpec() *DiscoverySpecApplyConfiguration {
	return &DiscoverySpecApplyConfiguration{}
}

// WithRemoteURL sets the RemoteURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteURL field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithRemoteURL(value string) *DiscoverySpecApplyConfiguration {
	b.RemoteURL = &value
	return b
}

// WithDiscoverySecretRef sets the DiscoverySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiscoverySecretRef field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithDiscoverySecretRef(value v1.LocalObjectReference) *DiscoverySpecApplyConfiguration {
	b.DiscoverySecretRef = &value
	return b
}

// WithReleaseSecretRef sets the ReleaseSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseSecretRef field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithReleaseSecretRef(value v1.LocalObjectReference) *DiscoverySpecApplyConfiguration {
	b.ReleaseSecretRef = &value
	return b
}

// WithCron sets the Cron field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cron field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithCron(value *CronApplyConfiguration) *DiscoverySpecApplyConfiguration {
	b.Cron = value
	return b
}

// WithDisableStartupDiscovery sets the DisableStartupDiscovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableStartupDiscovery field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithDisableStartupDiscovery(value bool) *DiscoverySpecApplyConfiguration {
	b.DisableStartupDiscovery = &value
	return b
}
