// Copyright 2025 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DiscoveryStatusApplyConfiguration represents a declarative configuration of the DiscoveryStatus type for use
// with apply.
type DiscoveryStatusApplyConfiguration struct {
	Phase         *string  `json:"phase,omitempty"`
	Message       *string  `json:"message,omitempty"`
	LastDiscovery *v1.Time `json:"lastDiscovery,omitempty"`
}

// DiscoveryStatusApplyConfiguration constructs a declarative configuration of the DiscoveryStatus type for use with
// apply.
func DiscoveryStatus() *DiscoveryStatusApplyConfiguration {
	return &DiscoveryStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *DiscoveryStatusApplyConfiguration) WithPhase(value string) *DiscoveryStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DiscoveryStatusApplyConfiguration) WithMessage(value string) *DiscoveryStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithLastDiscovery sets the LastDiscovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastDiscovery field is set to the value of the last call.
func (b *DiscoveryStatusApplyConfiguration) WithLastDiscovery(value v1.Time) *DiscoveryStatusApplyConfiguration {
	b.LastDiscovery = &value
	return b
}
