// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DiscoverySpecApplyConfiguration represents a declarative configuration of the DiscoverySpec type for use
// with apply.
type DiscoverySpecApplyConfiguration struct {
	Registry *RegistryApplyConfiguration        `json:"registry,omitempty"`
	Webhook  *WebhookApplyConfiguration         `json:"webhook,omitempty"`
	Config   *DiscoveryConfigApplyConfiguration `json:"config,omitempty"`
}

// DiscoverySpecApplyConfiguration constructs a declarative configuration of the DiscoverySpec type for use with
// apply.
func DiscoverySpec() *DiscoverySpecApplyConfiguration {
	return &DiscoverySpecApplyConfiguration{}
}

// WithRegistry sets the Registry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Registry field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithRegistry(value *RegistryApplyConfiguration) *DiscoverySpecApplyConfiguration {
	b.Registry = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithWebhook(value *WebhookApplyConfiguration) *DiscoverySpecApplyConfiguration {
	b.Webhook = value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *DiscoverySpecApplyConfiguration) WithConfig(value *DiscoveryConfigApplyConfiguration) *DiscoverySpecApplyConfiguration {
	b.Config = value
	return b
}
