// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DiscoveryStatusApplyConfiguration represents a declarative configuration of the DiscoveryStatus type for use
// with apply.
type DiscoveryStatusApplyConfiguration struct {
	PodGeneration *int64 `json:"podGeneration,omitempty"`
}

// DiscoveryStatusApplyConfiguration constructs a declarative configuration of the DiscoveryStatus type for use with
// apply.
func DiscoveryStatus() *DiscoveryStatusApplyConfiguration {
	return &DiscoveryStatusApplyConfiguration{}
}

// WithPodGeneration sets the PodGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGeneration field is set to the value of the last call.
func (b *DiscoveryStatusApplyConfiguration) WithPodGeneration(value int64) *DiscoveryStatusApplyConfiguration {
	b.PodGeneration = &value
	return b
}
