// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FilterApplyConfiguration represents a declarative configuration of the Filter type for use
// with apply.
type FilterApplyConfiguration struct {
	RepositoryPatterns []string `json:"repositoryPatterns,omitempty"`
}

// FilterApplyConfiguration constructs a declarative configuration of the Filter type for use with
// apply.
func Filter() *FilterApplyConfiguration {
	return &FilterApplyConfiguration{}
}

// WithRepositoryPatterns adds the given value to the RepositoryPatterns field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RepositoryPatterns field.
func (b *FilterApplyConfiguration) WithRepositoryPatterns(values ...string) *FilterApplyConfiguration {
	for i := range values {
		b.RepositoryPatterns = append(b.RepositoryPatterns, values[i])
	}
	return b
}
