// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HydratedTargetConfigApplyConfiguration represents a declarative configuration of the HydratedTargetConfig type for use
// with apply.
type HydratedTargetConfigApplyConfiguration struct {
	Chart *ChartConfigApplyConfiguration         `json:"chart,omitempty"`
	Input *HydratedTargetInputApplyConfiguration `json:"input,omitempty"`
}

// HydratedTargetConfigApplyConfiguration constructs a declarative configuration of the HydratedTargetConfig type for use with
// apply.
func HydratedTargetConfig() *HydratedTargetConfigApplyConfiguration {
	return &HydratedTargetConfigApplyConfiguration{}
}

// WithChart sets the Chart field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Chart field is set to the value of the last call.
func (b *HydratedTargetConfigApplyConfiguration) WithChart(value *ChartConfigApplyConfiguration) *HydratedTargetConfigApplyConfiguration {
	b.Chart = value
	return b
}

// WithInput sets the Input field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Input field is set to the value of the last call.
func (b *HydratedTargetConfigApplyConfiguration) WithInput(value *HydratedTargetInputApplyConfiguration) *HydratedTargetConfigApplyConfiguration {
	b.Input = value
	return b
}
