// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HydratedTargetStatusApplyConfiguration represents a declarative configuration of the HydratedTargetStatus type for use
// with apply.
type HydratedTargetStatusApplyConfiguration struct {
	Conditions      []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	JobRef          *corev1.ObjectReference          `json:"jobRef,omitempty"`
	ConfigSecretRef *corev1.ObjectReference          `json:"configSecretRef,omitempty"`
}

// HydratedTargetStatusApplyConfiguration constructs a declarative configuration of the HydratedTargetStatus type for use with
// apply.
func HydratedTargetStatus() *HydratedTargetStatusApplyConfiguration {
	return &HydratedTargetStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *HydratedTargetStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *HydratedTargetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithJobRef sets the JobRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobRef field is set to the value of the last call.
func (b *HydratedTargetStatusApplyConfiguration) WithJobRef(value corev1.ObjectReference) *HydratedTargetStatusApplyConfiguration {
	b.JobRef = &value
	return b
}

// WithConfigSecretRef sets the ConfigSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigSecretRef field is set to the value of the last call.
func (b *HydratedTargetStatusApplyConfiguration) WithConfigSecretRef(value corev1.ObjectReference) *HydratedTargetStatusApplyConfiguration {
	b.ConfigSecretRef = &value
	return b
}
