// Copyright 2025 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MaintainerApplyConfiguration represents a declarative configuration of the Maintainer type for use
// with apply.
type MaintainerApplyConfiguration struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

// MaintainerApplyConfiguration constructs a declarative configuration of the Maintainer type for use with
// apply.
func Maintainer() *MaintainerApplyConfiguration {
	return &MaintainerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MaintainerApplyConfiguration) WithName(value string) *MaintainerApplyConfiguration {
	b.Name = &value
	return b
}

// WithEmail sets the Email field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Email field is set to the value of the last call.
func (b *MaintainerApplyConfiguration) WithEmail(value string) *MaintainerApplyConfiguration {
	b.Email = &value
	return b
}
