// Copyright BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PreflightReportApplyConfiguration represents a declarative configuration of the PreflightReport type for use
// with apply.
//
// PreflightReport holds the agent's health-check results.
type PreflightReportApplyConfiguration struct {
	// Checks are sorted by Type so equal reports compare equal.
	Checks []PreflightCheckApplyConfiguration `json:"checks,omitempty"`
}

// PreflightReportApplyConfiguration constructs a declarative configuration of the PreflightReport type for use with
// apply.
func PreflightReport() *PreflightReportApplyConfiguration {
	return &PreflightReportApplyConfiguration{}
}

// WithChecks adds the given value to the Checks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Checks field.
func (b *PreflightReportApplyConfiguration) WithChecks(values ...*PreflightCheckApplyConfiguration) *PreflightReportApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithChecks")
		}
		b.Checks = append(b.Checks, *values[i])
	}
	return b
}
