// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ReferenceGrantFromSubjectApplyConfiguration represents a declarative configuration of the ReferenceGrantFromSubject type for use
// with apply.
//
// ReferenceGrantFromSubject identifies the group, kind, and namespace of a resource that
// is permitted to reference resources in the namespace where the ReferenceGrant lives.
type ReferenceGrantFromSubjectApplyConfiguration struct {
	// Group is the API group of the referencing resource.
	// Use "" for the core API group.
	Group *string `json:"group,omitempty"`
	// Kind is the kind of the referencing resource (e.g. "Profile", "Target").
	Kind *string `json:"kind,omitempty"`
	// Namespace is the namespace of the referencing resource.
	// A single namespace is allowed per From entry to avoid overly broad grants.
	Namespace *string `json:"namespace,omitempty"`
}

// ReferenceGrantFromSubjectApplyConfiguration constructs a declarative configuration of the ReferenceGrantFromSubject type for use with
// apply.
func ReferenceGrantFromSubject() *ReferenceGrantFromSubjectApplyConfiguration {
	return &ReferenceGrantFromSubjectApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ReferenceGrantFromSubjectApplyConfiguration) WithGroup(value string) *ReferenceGrantFromSubjectApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ReferenceGrantFromSubjectApplyConfiguration) WithKind(value string) *ReferenceGrantFromSubjectApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ReferenceGrantFromSubjectApplyConfiguration) WithNamespace(value string) *ReferenceGrantFromSubjectApplyConfiguration {
	b.Namespace = &value
	return b
}
