// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RegistrySpecApplyConfiguration represents a declarative configuration of the RegistrySpec type for use
// with apply.
//
// RegistrySpec defines the desired state of a Registry.
type RegistrySpecApplyConfiguration struct {
	// Hostname is the registry endpoint (e.g. "registry.example.com:5000").
	Hostname *string `json:"hostname,omitempty"`
	// PlainHTTP uses HTTP instead of HTTPS for connections to this registry.
	PlainHTTP *bool `json:"plainHTTP,omitempty"`
	// SolarSecretRef references a Secret in the same namespace with credentials
	// to access this registry from the SolAr cluster. Required if this registry
	// is used as a render target.
	SolarSecretRef *v1.LocalObjectReference `json:"solarSecretRef,omitempty"`
	// TargetPullSecretName is the name of the Secret on the target cluster that
	// contains credentials to pull from this registry. SolAr renders this name
	// into target manifests (e.g. Flux OCIRepository.spec.secretRef.name) but
	// never reads the Secret itself. The cluster maintainer must provision a
	// Secret with this name on each target. Omit for anonymous pull.
	TargetPullSecretName *string `json:"targetPullSecretName,omitempty"`
	// Flavor identifies the registry type for discovery webhook routing (e.g. "zot").
	// Required when WebhookPath is set.
	Flavor *string `json:"flavor,omitempty"`
	// WebhookPath is the HTTP path on which the discovery worker listens for
	// push notifications from this registry. Leave empty to disable webhook-based
	// discovery; set ScanInterval to enable scan mode instead.
	WebhookPath *string `json:"webhookPath,omitempty"`
	// ScanInterval controls how often the discovery worker performs a full scan
	// of this registry. Leave unset to disable scan mode entirely.
	ScanInterval *metav1.Duration `json:"scanInterval,omitempty"`
}

// RegistrySpecApplyConfiguration constructs a declarative configuration of the RegistrySpec type for use with
// apply.
func RegistrySpec() *RegistrySpecApplyConfiguration {
	return &RegistrySpecApplyConfiguration{}
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithHostname(value string) *RegistrySpecApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithPlainHTTP sets the PlainHTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PlainHTTP field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithPlainHTTP(value bool) *RegistrySpecApplyConfiguration {
	b.PlainHTTP = &value
	return b
}

// WithSolarSecretRef sets the SolarSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SolarSecretRef field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithSolarSecretRef(value v1.LocalObjectReference) *RegistrySpecApplyConfiguration {
	b.SolarSecretRef = &value
	return b
}

// WithTargetPullSecretName sets the TargetPullSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPullSecretName field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithTargetPullSecretName(value string) *RegistrySpecApplyConfiguration {
	b.TargetPullSecretName = &value
	return b
}

// WithFlavor sets the Flavor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Flavor field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithFlavor(value string) *RegistrySpecApplyConfiguration {
	b.Flavor = &value
	return b
}

// WithWebhookPath sets the WebhookPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookPath field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithWebhookPath(value string) *RegistrySpecApplyConfiguration {
	b.WebhookPath = &value
	return b
}

// WithScanInterval sets the ScanInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScanInterval field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithScanInterval(value metav1.Duration) *RegistrySpecApplyConfiguration {
	b.ScanInterval = &value
	return b
}
