// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RegistrySpecApplyConfiguration represents a declarative configuration of the RegistrySpec type for use
// with apply.
//
// RegistrySpec defines the desired state of a Registry.
type RegistrySpecApplyConfiguration struct {
	// Hostname is the registry endpoint (e.g. "registry.example.com:5000").
	Hostname *string `json:"hostname,omitempty"`
	// PlainHTTP uses HTTP instead of HTTPS for connections to this registry.
	PlainHTTP *bool `json:"plainHTTP,omitempty"`
	// SolarSecretRef references a Secret in the same namespace with credentials
	// to access this registry from the SolAr cluster. Required if this registry
	// is used as a render target.
	SolarSecretRef *v1.LocalObjectReference `json:"solarSecretRef,omitempty"`
	// TargetSecretRef describes where the credentials secret lives in the target cluster.
	// Used by the target agent for pull access.
	TargetSecretRef *TargetSecretReferenceApplyConfiguration `json:"targetSecretRef,omitempty"`
}

// RegistrySpecApplyConfiguration constructs a declarative configuration of the RegistrySpec type for use with
// apply.
func RegistrySpec() *RegistrySpecApplyConfiguration {
	return &RegistrySpecApplyConfiguration{}
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithHostname(value string) *RegistrySpecApplyConfiguration {
	b.Hostname = &value
	return b
}

// WithPlainHTTP sets the PlainHTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PlainHTTP field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithPlainHTTP(value bool) *RegistrySpecApplyConfiguration {
	b.PlainHTTP = &value
	return b
}

// WithSolarSecretRef sets the SolarSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SolarSecretRef field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithSolarSecretRef(value v1.LocalObjectReference) *RegistrySpecApplyConfiguration {
	b.SolarSecretRef = &value
	return b
}

// WithTargetSecretRef sets the TargetSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetSecretRef field is set to the value of the last call.
func (b *RegistrySpecApplyConfiguration) WithTargetSecretRef(value *TargetSecretReferenceApplyConfiguration) *RegistrySpecApplyConfiguration {
	b.TargetSecretRef = value
	return b
}
