// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RegistryBindingSpecApplyConfiguration represents a declarative configuration of the RegistryBindingSpec type for use
// with apply.
//
// RegistryBindingSpec defines the desired state of a RegistryBinding.
type RegistryBindingSpecApplyConfiguration struct {
	// TargetRef references the Target this binding applies to.
	TargetRef *v1.LocalObjectReference `json:"targetRef,omitempty"`
	// RegistryRef references the Registry being bound.
	RegistryRef *v1.LocalObjectReference `json:"registryRef,omitempty"`
}

// RegistryBindingSpecApplyConfiguration constructs a declarative configuration of the RegistryBindingSpec type for use with
// apply.
func RegistryBindingSpec() *RegistryBindingSpecApplyConfiguration {
	return &RegistryBindingSpecApplyConfiguration{}
}

// WithTargetRef sets the TargetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRef field is set to the value of the last call.
func (b *RegistryBindingSpecApplyConfiguration) WithTargetRef(value v1.LocalObjectReference) *RegistryBindingSpecApplyConfiguration {
	b.TargetRef = &value
	return b
}

// WithRegistryRef sets the RegistryRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegistryRef field is set to the value of the last call.
func (b *RegistryBindingSpecApplyConfiguration) WithRegistryRef(value v1.LocalObjectReference) *RegistryBindingSpecApplyConfiguration {
	b.RegistryRef = &value
	return b
}
