// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RegistryBindingRewriteApplyConfiguration represents a declarative configuration of the RegistryBindingRewrite type for use
// with apply.
//
// RegistryBindingRewrite describes how to rewrite OCI repository references
// when resources are fetched on the target cluster.
type RegistryBindingRewriteApplyConfiguration struct {
	// SourceEndpoint is the original registry host to match (e.g. "ghcr.io").
	SourceEndpoint *string `json:"sourceEndpoint,omitempty"`
	// RepositoryPrefix is prepended to the repository path after rewriting.
	RepositoryPrefix *string `json:"repositoryPrefix,omitempty"`
}

// RegistryBindingRewriteApplyConfiguration constructs a declarative configuration of the RegistryBindingRewrite type for use with
// apply.
func RegistryBindingRewrite() *RegistryBindingRewriteApplyConfiguration {
	return &RegistryBindingRewriteApplyConfiguration{}
}

// WithSourceEndpoint sets the SourceEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceEndpoint field is set to the value of the last call.
func (b *RegistryBindingRewriteApplyConfiguration) WithSourceEndpoint(value string) *RegistryBindingRewriteApplyConfiguration {
	b.SourceEndpoint = &value
	return b
}

// WithRepositoryPrefix sets the RepositoryPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryPrefix field is set to the value of the last call.
func (b *RegistryBindingRewriteApplyConfiguration) WithRepositoryPrefix(value string) *RegistryBindingRewriteApplyConfiguration {
	b.RepositoryPrefix = &value
	return b
}
