// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RegistryApplyConfiguration represents a declarative configuration of the Registry type for use
// with apply.
type RegistryApplyConfiguration struct {
	RegistryURL        *string                  `json:"registryURL,omitempty"`
	DiscoverySecretRef *v1.LocalObjectReference `json:"discoverySecretRef,omitempty"`
	ReleaseSecretRef   *v1.LocalObjectReference `json:"releaseSecretRef,omitempty"`
}

// RegistryApplyConfiguration constructs a declarative configuration of the Registry type for use with
// apply.
func Registry() *RegistryApplyConfiguration {
	return &RegistryApplyConfiguration{}
}

// WithRegistryURL sets the RegistryURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegistryURL field is set to the value of the last call.
func (b *RegistryApplyConfiguration) WithRegistryURL(value string) *RegistryApplyConfiguration {
	b.RegistryURL = &value
	return b
}

// WithDiscoverySecretRef sets the DiscoverySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiscoverySecretRef field is set to the value of the last call.
func (b *RegistryApplyConfiguration) WithDiscoverySecretRef(value v1.LocalObjectReference) *RegistryApplyConfiguration {
	b.DiscoverySecretRef = &value
	return b
}

// WithReleaseSecretRef sets the ReleaseSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseSecretRef field is set to the value of the last call.
func (b *RegistryApplyConfiguration) WithReleaseSecretRef(value v1.LocalObjectReference) *RegistryApplyConfiguration {
	b.ReleaseSecretRef = &value
	return b
}
