// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ReleaseSpecApplyConfiguration represents a declarative configuration of the ReleaseSpec type for use
// with apply.
//
// ReleaseSpec defines the desired state of a Release.
// It specifies which component version to release and its deployment configuration.
type ReleaseSpecApplyConfiguration struct {
	// ComponentVersionRef is a reference to the ComponentVersion to be released.
	// It points to the specific version of a component that this release is based on.
	ComponentVersionRef *v1.LocalObjectReference `json:"componentVersionRef,omitempty"`
	// TargetNamespace is the namespace the ComponentVersion gets deployed to.
	TargetNamespace *string `json:"targetNamespace,omitempty"`
	// UniqueName is a logical identifier used to ensure this component is deployed
	// only once per target cluster when multiple Profiles match the same target.
	UniqueName *string `json:"uniqueName,omitempty"`
	// AntiAffinity defines exclusion rules. If another Release matching this
	// label selector is already bound to the same Target, this Release should
	// not be deployed there (or a conflict condition should be raised).
	AntiAffinity *metav1.LabelSelectorApplyConfiguration `json:"antiAffinity,omitempty"`
	// Values contains deployment-specific values or configuration for the release.
	// These values override defaults from the component version and are used during deployment.
	Values *runtime.RawExtension `json:"values,omitempty"`
	// failedJobTTL is the TTL in seconds after which a failed render job and its secrets are cleaned up.
	// After this duration, the Kubernetes TTL controller will delete the Job and the controller will delete
	// the Secrets (ConfigSecret, AuthSecret). On success, Job and Secrets are deleted immediately.
	// If not set, defaults to 3600 (1 hour).
	FailedJobTTL *int32 `json:"failedJobTTL,omitempty"`
}

// ReleaseSpecApplyConfiguration constructs a declarative configuration of the ReleaseSpec type for use with
// apply.
func ReleaseSpec() *ReleaseSpecApplyConfiguration {
	return &ReleaseSpecApplyConfiguration{}
}

// WithComponentVersionRef sets the ComponentVersionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ComponentVersionRef field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithComponentVersionRef(value v1.LocalObjectReference) *ReleaseSpecApplyConfiguration {
	b.ComponentVersionRef = &value
	return b
}

// WithTargetNamespace sets the TargetNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetNamespace field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithTargetNamespace(value string) *ReleaseSpecApplyConfiguration {
	b.TargetNamespace = &value
	return b
}

// WithUniqueName sets the UniqueName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UniqueName field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithUniqueName(value string) *ReleaseSpecApplyConfiguration {
	b.UniqueName = &value
	return b
}

// WithAntiAffinity sets the AntiAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AntiAffinity field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithAntiAffinity(value *metav1.LabelSelectorApplyConfiguration) *ReleaseSpecApplyConfiguration {
	b.AntiAffinity = value
	return b
}

// WithValues sets the Values field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Values field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithValues(value runtime.RawExtension) *ReleaseSpecApplyConfiguration {
	b.Values = &value
	return b
}

// WithFailedJobTTL sets the FailedJobTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedJobTTL field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithFailedJobTTL(value int32) *ReleaseSpecApplyConfiguration {
	b.FailedJobTTL = &value
	return b
}
