// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ReleaseBindingStatusApplyConfiguration represents a declarative configuration of the ReleaseBindingStatus type for use
// with apply.
//
// ReleaseBindingStatus defines the observed state of a ReleaseBinding.
type ReleaseBindingStatusApplyConfiguration struct {
	// Conditions represent the latest available observations of a ReleaseBinding's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ReleaseBindingStatusApplyConfiguration constructs a declarative configuration of the ReleaseBindingStatus type for use with
// apply.
func ReleaseBindingStatus() *ReleaseBindingStatusApplyConfiguration {
	return &ReleaseBindingStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ReleaseBindingStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ReleaseBindingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
