// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ReleaseSpecApplyConfiguration represents a declarative configuration of the ReleaseSpec type for use
// with apply.
type ReleaseSpecApplyConfiguration struct {
	ComponentVersionRef *v1.LocalObjectReference `json:"componentRef,omitempty"`
	Values              *runtime.RawExtension    `json:"spec,omitempty"`
}

// ReleaseSpecApplyConfiguration constructs a declarative configuration of the ReleaseSpec type for use with
// apply.
func ReleaseSpec() *ReleaseSpecApplyConfiguration {
	return &ReleaseSpecApplyConfiguration{}
}

// WithComponentVersionRef sets the ComponentVersionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ComponentVersionRef field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithComponentVersionRef(value v1.LocalObjectReference) *ReleaseSpecApplyConfiguration {
	b.ComponentVersionRef = &value
	return b
}

// WithValues sets the Values field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Values field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithValues(value runtime.RawExtension) *ReleaseSpecApplyConfiguration {
	b.Values = &value
	return b
}
