// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
)

// ReleaseInputApplyConfiguration represents a declarative configuration of the ReleaseInput type for use
// with apply.
type ReleaseInputApplyConfiguration struct {
	Component  *ReleaseComponentApplyConfiguration         `json:"component,omitempty"`
	Resources  map[string]ResourceAccessApplyConfiguration `json:"resources,omitempty"`
	Entrypoint *solarv1alpha1.Entrypoint                   `json:"entrypoint,omitempty"`
}

// ReleaseInputApplyConfiguration constructs a declarative configuration of the ReleaseInput type for use with
// apply.
func ReleaseInput() *ReleaseInputApplyConfiguration {
	return &ReleaseInputApplyConfiguration{}
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *ReleaseInputApplyConfiguration) WithComponent(value *ReleaseComponentApplyConfiguration) *ReleaseInputApplyConfiguration {
	b.Component = value
	return b
}

// WithResources puts the entries into the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Resources field,
// overwriting an existing map entries in Resources field with the same key.
func (b *ReleaseInputApplyConfiguration) WithResources(entries map[string]ResourceAccessApplyConfiguration) *ReleaseInputApplyConfiguration {
	if b.Resources == nil && len(entries) > 0 {
		b.Resources = make(map[string]ResourceAccessApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Resources[k] = v
	}
	return b
}

// WithEntrypoint sets the Entrypoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Entrypoint field is set to the value of the last call.
func (b *ReleaseInputApplyConfiguration) WithEntrypoint(value solarv1alpha1.Entrypoint) *ReleaseInputApplyConfiguration {
	b.Entrypoint = &value
	return b
}
