// Copyright BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ReleaseReportApplyConfiguration represents a declarative configuration of the ReleaseReport type for use
// with apply.
//
// ReleaseReport is one bound Release's rolled-up state as reported by the agent.
type ReleaseReportApplyConfiguration struct {
	// Name is the untruncated Release name.
	Name *string `json:"name,omitempty"`
	// Namespace is where the OCIRepository/HelmRelease pair lives.
	Namespace *string `json:"namespace,omitempty"`
	// Phase is the mutually-exclusive lifecycle state.
	Phase *solarv1alpha1.ReleasePhase `json:"phase,omitempty"`
	// Revision is the chart version actually live, if known.
	Revision *string `json:"revision,omitempty"`
	// SourceConditions and HelmConditions are the verbatim Flux conditions of
	// the pair, kept apart so a fetch/verify failure stays distinguishable
	// from an apply failure.
	SourceConditions []v1.ConditionApplyConfiguration `json:"sourceConditions,omitempty"`
	HelmConditions   []v1.ConditionApplyConfiguration `json:"helmConditions,omitempty"`
}

// ReleaseReportApplyConfiguration constructs a declarative configuration of the ReleaseReport type for use with
// apply.
func ReleaseReport() *ReleaseReportApplyConfiguration {
	return &ReleaseReportApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ReleaseReportApplyConfiguration) WithName(value string) *ReleaseReportApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ReleaseReportApplyConfiguration) WithNamespace(value string) *ReleaseReportApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ReleaseReportApplyConfiguration) WithPhase(value solarv1alpha1.ReleasePhase) *ReleaseReportApplyConfiguration {
	b.Phase = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ReleaseReportApplyConfiguration) WithRevision(value string) *ReleaseReportApplyConfiguration {
	b.Revision = &value
	return b
}

// WithSourceConditions adds the given value to the SourceConditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SourceConditions field.
func (b *ReleaseReportApplyConfiguration) WithSourceConditions(values ...*v1.ConditionApplyConfiguration) *ReleaseReportApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSourceConditions")
		}
		b.SourceConditions = append(b.SourceConditions, *values[i])
	}
	return b
}

// WithHelmConditions adds the given value to the HelmConditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HelmConditions field.
func (b *ReleaseReportApplyConfiguration) WithHelmConditions(values ...*v1.ConditionApplyConfiguration) *ReleaseReportApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHelmConditions")
		}
		b.HelmConditions = append(b.HelmConditions, *values[i])
	}
	return b
}
