// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ReleaseSpecApplyConfiguration represents a declarative configuration of the ReleaseSpec type for use
// with apply.
//
// ReleaseSpec defines the desired state of a Release.
// It specifies which component version to release and its deployment configuration.
type ReleaseSpecApplyConfiguration struct {
	// ComponentVersionRef is a reference to the ComponentVersion to be released.
	// It points to the specific version of a component that this release is based on.
	ComponentVersionRef *v1.LocalObjectReference `json:"componentRef,omitempty"`
	// Values contains deployment-specific values or configuration for the release.
	// These values override defaults from the component version and are used during deployment.
	Values *runtime.RawExtension `json:"values,omitempty"`
	// failedJobTTL is the TTL in seconds for the Kubernetes TTL controller to clean up a failed render job.
	// After this duration, the Kubernetes TTL controller will delete the Job.
	// Secrets (ConfigSecret, AuthSecret) are cleaned up separately by the controller
	// when the parent Release is deleted or when the job succeeds.
	// If not set, defaults to 3600 (1 hour).
	FailedJobTTL *int32 `json:"failedJobTTL,omitempty"`
}

// ReleaseSpecApplyConfiguration constructs a declarative configuration of the ReleaseSpec type for use with
// apply.
func ReleaseSpec() *ReleaseSpecApplyConfiguration {
	return &ReleaseSpecApplyConfiguration{}
}

// WithComponentVersionRef sets the ComponentVersionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ComponentVersionRef field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithComponentVersionRef(value v1.LocalObjectReference) *ReleaseSpecApplyConfiguration {
	b.ComponentVersionRef = &value
	return b
}

// WithValues sets the Values field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Values field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithValues(value runtime.RawExtension) *ReleaseSpecApplyConfiguration {
	b.Values = &value
	return b
}

// WithFailedJobTTL sets the FailedJobTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedJobTTL field is set to the value of the last call.
func (b *ReleaseSpecApplyConfiguration) WithFailedJobTTL(value int32) *ReleaseSpecApplyConfiguration {
	b.FailedJobTTL = &value
	return b
}
