// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ReleaseBindingSpecApplyConfiguration represents a declarative configuration of the ReleaseBindingSpec type for use
// with apply.
//
// ReleaseBindingSpec defines the desired state of a ReleaseBinding.
type ReleaseBindingSpecApplyConfiguration struct {
	// TargetRef references the Target this release is bound to.
	TargetRef *v1.LocalObjectReference `json:"targetRef,omitempty"`
	// ReleaseRef references the Release to deploy.
	ReleaseRef *v1.LocalObjectReference `json:"releaseRef,omitempty"`
}

// ReleaseBindingSpecApplyConfiguration constructs a declarative configuration of the ReleaseBindingSpec type for use with
// apply.
func ReleaseBindingSpec() *ReleaseBindingSpecApplyConfiguration {
	return &ReleaseBindingSpecApplyConfiguration{}
}

// WithTargetRef sets the TargetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRef field is set to the value of the last call.
func (b *ReleaseBindingSpecApplyConfiguration) WithTargetRef(value v1.LocalObjectReference) *ReleaseBindingSpecApplyConfiguration {
	b.TargetRef = &value
	return b
}

// WithReleaseRef sets the ReleaseRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseRef field is set to the value of the last call.
func (b *ReleaseBindingSpecApplyConfiguration) WithReleaseRef(value v1.LocalObjectReference) *ReleaseBindingSpecApplyConfiguration {
	b.ReleaseRef = &value
	return b
}
