// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
)

// RendererConfigApplyConfiguration represents a declarative configuration of the RendererConfig type for use
// with apply.
type RendererConfigApplyConfiguration struct {
	Type                 *solarv1alpha1.RendererConfigType       `json:"type,omitempty"`
	ReleaseConfig        *ReleaseConfigApplyConfiguration        `json:"release,omitempty"`
	HydratedTargetConfig *HydratedTargetConfigApplyConfiguration `json:"hydrated-target,omitempty"`
	PushOptions          *PushOptionsApplyConfiguration          `json:"push,omitempty"`
}

// RendererConfigApplyConfiguration constructs a declarative configuration of the RendererConfig type for use with
// apply.
func RendererConfig() *RendererConfigApplyConfiguration {
	return &RendererConfigApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RendererConfigApplyConfiguration) WithType(value solarv1alpha1.RendererConfigType) *RendererConfigApplyConfiguration {
	b.Type = &value
	return b
}

// WithReleaseConfig sets the ReleaseConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseConfig field is set to the value of the last call.
func (b *RendererConfigApplyConfiguration) WithReleaseConfig(value *ReleaseConfigApplyConfiguration) *RendererConfigApplyConfiguration {
	b.ReleaseConfig = value
	return b
}

// WithHydratedTargetConfig sets the HydratedTargetConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HydratedTargetConfig field is set to the value of the last call.
func (b *RendererConfigApplyConfiguration) WithHydratedTargetConfig(value *HydratedTargetConfigApplyConfiguration) *RendererConfigApplyConfiguration {
	b.HydratedTargetConfig = value
	return b
}

// WithPushOptions sets the PushOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PushOptions field is set to the value of the last call.
func (b *RendererConfigApplyConfiguration) WithPushOptions(value *PushOptionsApplyConfiguration) *RendererConfigApplyConfiguration {
	b.PushOptions = value
	return b
}
