// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RenderBindingSpecApplyConfiguration represents a declarative configuration of the RenderBindingSpec type for use
// with apply.
//
// RenderBindingSpec links a consumer resource to a RenderArtifact for ref-counting.
type RenderBindingSpecApplyConfiguration struct {
	// RenderArtifactRef is the name of the RenderArtifact in the same namespace.
	RenderArtifactRef *v1.LocalObjectReference `json:"renderArtifactRef,omitempty"`
	// OwnerKind is the kind of the consuming resource (e.g. "Target").
	OwnerKind *string `json:"ownerKind,omitempty"`
	// OwnerName is the name of the consuming resource.
	OwnerName *string `json:"ownerName,omitempty"`
	// OwnerNamespace is the namespace of the consuming resource.
	OwnerNamespace *string `json:"ownerNamespace,omitempty"`
}

// RenderBindingSpecApplyConfiguration constructs a declarative configuration of the RenderBindingSpec type for use with
// apply.
func RenderBindingSpec() *RenderBindingSpecApplyConfiguration {
	return &RenderBindingSpecApplyConfiguration{}
}

// WithRenderArtifactRef sets the RenderArtifactRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenderArtifactRef field is set to the value of the last call.
func (b *RenderBindingSpecApplyConfiguration) WithRenderArtifactRef(value v1.LocalObjectReference) *RenderBindingSpecApplyConfiguration {
	b.RenderArtifactRef = &value
	return b
}

// WithOwnerKind sets the OwnerKind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerKind field is set to the value of the last call.
func (b *RenderBindingSpecApplyConfiguration) WithOwnerKind(value string) *RenderBindingSpecApplyConfiguration {
	b.OwnerKind = &value
	return b
}

// WithOwnerName sets the OwnerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerName field is set to the value of the last call.
func (b *RenderBindingSpecApplyConfiguration) WithOwnerName(value string) *RenderBindingSpecApplyConfiguration {
	b.OwnerName = &value
	return b
}

// WithOwnerNamespace sets the OwnerNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerNamespace field is set to the value of the last call.
func (b *RenderBindingSpecApplyConfiguration) WithOwnerNamespace(value string) *RenderBindingSpecApplyConfiguration {
	b.OwnerNamespace = &value
	return b
}
