// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// RenderTaskSpecApplyConfiguration represents a declarative configuration of the RenderTaskSpec type for use
// with apply.
//
// RenderTaskSpec holds the specification for a RenderTask
type RenderTaskSpecApplyConfiguration struct {
	// RendererConfig is the config used for the renderer job
	RendererConfigApplyConfiguration `json:",inline"`
	// Repository is the Repository where the chart will be pushed to (e.g. charts/mychart)
	Repository *string `json:"repository,omitempty"`
	// Tag is the Tag of the helm chart to be pushed.
	// Make sure that the tag matches the version in Chart.yaml, otherwise helm
	// will error before pushing.
	Tag *string `json:"tag,omitempty"`
	// BaseURL is the registry URL to push the rendered chart to (e.g. "registry.example.com:5000").
	BaseURL *string `json:"baseURL,omitempty"`
	// Insecure uses plain HTTP instead of HTTPS for pushing to the registry.
	Insecure *bool `json:"insecure,omitempty"`
	// SecretRef references a Secret in the same namespace with registry credentials
	// for pushing the rendered chart.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
	// failedJobTTL is the TTL in seconds after which a failed render job and its secrets are cleaned up.
	// After this duration, the Kubernetes TTL controller will delete the Job and the controller will delete
	// the Secrets (ConfigSecret, AuthSecret). On success, Job and Secrets are deleted immediately.
	// If not set, defaults to 3600 (1 hour).
	FailedJobTTL *int32 `json:"failedJobTTL,omitempty"`
	// OwnerName is the name of the resource that created this RenderTask.
	OwnerName *string `json:"ownerName,omitempty"`
	// OwnerNamespace is the namespace of the resource that created this RenderTask.
	OwnerNamespace *string `json:"ownerNamespace,omitempty"`
	// OwnerKind is the kind of the resource that created this RenderTask (e.g. Release, Target).
	OwnerKind *string `json:"ownerKind,omitempty"`
}

// RenderTaskSpecApplyConfiguration constructs a declarative configuration of the RenderTaskSpec type for use with
// apply.
func RenderTaskSpec() *RenderTaskSpecApplyConfiguration {
	return &RenderTaskSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithType(value solarv1alpha1.RendererConfigType) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.Type = &value
	return b
}

// WithReleaseConfig sets the ReleaseConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseConfig field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithReleaseConfig(value *ReleaseConfigApplyConfiguration) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.ReleaseConfig = value
	return b
}

// WithBootstrapConfig sets the BootstrapConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootstrapConfig field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithBootstrapConfig(value *BootstrapConfigApplyConfiguration) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.BootstrapConfig = value
	return b
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithRepository(value string) *RenderTaskSpecApplyConfiguration {
	b.Repository = &value
	return b
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithTag(value string) *RenderTaskSpecApplyConfiguration {
	b.Tag = &value
	return b
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithBaseURL(value string) *RenderTaskSpecApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithInsecure sets the Insecure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Insecure field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithInsecure(value bool) *RenderTaskSpecApplyConfiguration {
	b.Insecure = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *RenderTaskSpecApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithFailedJobTTL sets the FailedJobTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedJobTTL field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithFailedJobTTL(value int32) *RenderTaskSpecApplyConfiguration {
	b.FailedJobTTL = &value
	return b
}

// WithOwnerName sets the OwnerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerName field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithOwnerName(value string) *RenderTaskSpecApplyConfiguration {
	b.OwnerName = &value
	return b
}

// WithOwnerNamespace sets the OwnerNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerNamespace field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithOwnerNamespace(value string) *RenderTaskSpecApplyConfiguration {
	b.OwnerNamespace = &value
	return b
}

// WithOwnerKind sets the OwnerKind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerKind field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithOwnerKind(value string) *RenderTaskSpecApplyConfiguration {
	b.OwnerKind = &value
	return b
}
