// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
)

// RenderTaskSpecApplyConfiguration represents a declarative configuration of the RenderTaskSpec type for use
// with apply.
//
// RenderTaskSpec holds the specification for a RenderTask
type RenderTaskSpecApplyConfiguration struct {
	// RendererConfig is the config used for the renderer job
	RendererConfigApplyConfiguration `json:",inline"`
	// Reference is the Reference where the chart will be pushed to (e.g., charts/mychart:v0.1.0)
	// Keep in mind that:
	// - the reference gets automatically prefixed with the registry by the rendertask-controller.
	// - the tag matches the version in Chart.yaml, otherwise helm will error before pushing.
	Reference *string `json:"reference,omitempty"`
}

// RenderTaskSpecApplyConfiguration constructs a declarative configuration of the RenderTaskSpec type for use with
// apply.
func RenderTaskSpec() *RenderTaskSpecApplyConfiguration {
	return &RenderTaskSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithType(value solarv1alpha1.RendererConfigType) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.Type = &value
	return b
}

// WithReleaseConfig sets the ReleaseConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseConfig field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithReleaseConfig(value *ReleaseConfigApplyConfiguration) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.ReleaseConfig = value
	return b
}

// WithHydratedTargetConfig sets the HydratedTargetConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HydratedTargetConfig field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithHydratedTargetConfig(value *HydratedTargetConfigApplyConfiguration) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.HydratedTargetConfig = value
	return b
}

// WithReference sets the Reference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reference field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithReference(value string) *RenderTaskSpecApplyConfiguration {
	b.Reference = &value
	return b
}
