// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
)

// RenderTaskSpecApplyConfiguration represents a declarative configuration of the RenderTaskSpec type for use
// with apply.
//
// RenderTaskSpec holds the specification for a RenderTask
type RenderTaskSpecApplyConfiguration struct {
	// RendererConfig is the config used for the renderer job
	RendererConfigApplyConfiguration `json:",inline"`
	// Repository is the Repository where the chart will be pushed to (e.g. charts/mychart)
	// Keep in mind that the repository gets automatically prefixed with the
	// registry by the rendertask-controller.
	Repository *string `json:"repository,omitempty"`
	// Tag is the Tag of the helm chart to be pushed.
	// Make sure that the tag matches the version in Chart.yaml, otherwise helm
	// will error before pushing.
	Tag *string `json:"tag,omitempty"`
	// failedJobTTL is the TTL in seconds for cleaning up secrets after a failed render job.
	// After a render job fails and the job itself is deleted by the Kubernetes TTL controller,
	// the ConfigSecret and AuthSecret will be cleaned up by this controller.
	// The Job itself is cleaned up by the Kubernetes TTL controller based on the failedJobTTL value.
	// If not set, defaults to 3600 (1 hour).
	FailedJobTTL *int32 `json:"failedJobTTL,omitempty"`
}

// RenderTaskSpecApplyConfiguration constructs a declarative configuration of the RenderTaskSpec type for use with
// apply.
func RenderTaskSpec() *RenderTaskSpecApplyConfiguration {
	return &RenderTaskSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithType(value solarv1alpha1.RendererConfigType) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.Type = &value
	return b
}

// WithReleaseConfig sets the ReleaseConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseConfig field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithReleaseConfig(value *ReleaseConfigApplyConfiguration) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.ReleaseConfig = value
	return b
}

// WithHydratedTargetConfig sets the HydratedTargetConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HydratedTargetConfig field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithHydratedTargetConfig(value *HydratedTargetConfigApplyConfiguration) *RenderTaskSpecApplyConfiguration {
	b.RendererConfigApplyConfiguration.HydratedTargetConfig = value
	return b
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithRepository(value string) *RenderTaskSpecApplyConfiguration {
	b.Repository = &value
	return b
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithTag(value string) *RenderTaskSpecApplyConfiguration {
	b.Tag = &value
	return b
}

// WithFailedJobTTL sets the FailedJobTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedJobTTL field is set to the value of the last call.
func (b *RenderTaskSpecApplyConfiguration) WithFailedJobTTL(value int32) *RenderTaskSpecApplyConfiguration {
	b.FailedJobTTL = &value
	return b
}
