// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ResolvedResourceAccessApplyConfiguration represents a declarative configuration of the ResolvedResourceAccess type for use
// with apply.
//
// ResolvedResourceAccess extends ResourceAccess with pull secret information
// resolved from RegistryBindings at render time.
type ResolvedResourceAccessApplyConfiguration struct {
	// Repository of the Resource.
	Repository *string `json:"repository,omitempty"`
	// Insecure switches TLS/HTTPS off if true
	Insecure *bool `json:"insecure,omitempty"`
	// Tag of the Resource.
	Tag *string `json:"tag,omitempty"`
	// Helm contains metadata for Helm chart resources, populated during discovery.
	Helm *HelmResourceMetadataApplyConfiguration `json:"helm,omitempty"`
	// PullSecretName is the name of the pull secret on the target cluster for
	// this resource's registry. Resolved from Registry.spec.targetPullSecretName
	// via RegistryBinding. Empty means anonymous pull.
	PullSecretName *string `json:"pullSecretName,omitempty"`
}

// ResolvedResourceAccessApplyConfiguration constructs a declarative configuration of the ResolvedResourceAccess type for use with
// apply.
func ResolvedResourceAccess() *ResolvedResourceAccessApplyConfiguration {
	return &ResolvedResourceAccessApplyConfiguration{}
}

// WithRepository sets the Repository field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repository field is set to the value of the last call.
func (b *ResolvedResourceAccessApplyConfiguration) WithRepository(value string) *ResolvedResourceAccessApplyConfiguration {
	b.Repository = &value
	return b
}

// WithInsecure sets the Insecure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Insecure field is set to the value of the last call.
func (b *ResolvedResourceAccessApplyConfiguration) WithInsecure(value bool) *ResolvedResourceAccessApplyConfiguration {
	b.Insecure = &value
	return b
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *ResolvedResourceAccessApplyConfiguration) WithTag(value string) *ResolvedResourceAccessApplyConfiguration {
	b.Tag = &value
	return b
}

// WithHelm sets the Helm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Helm field is set to the value of the last call.
func (b *ResolvedResourceAccessApplyConfiguration) WithHelm(value *HelmResourceMetadataApplyConfiguration) *ResolvedResourceAccessApplyConfiguration {
	b.Helm = value
	return b
}

// WithPullSecretName sets the PullSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullSecretName field is set to the value of the last call.
func (b *ResolvedResourceAccessApplyConfiguration) WithPullSecretName(value string) *ResolvedResourceAccessApplyConfiguration {
	b.PullSecretName = &value
	return b
}
