// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TargetStatusApplyConfiguration represents a declarative configuration of the TargetStatus type for use
// with apply.
type TargetStatusApplyConfiguration struct {
	Conditions      []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	JobRef          *corev1.ObjectReference          `json:"jobRef,omitempty"`
	ConfigSecretRef *corev1.ObjectReference          `json:"configSecretRef,omitempty"`
}

// TargetStatusApplyConfiguration constructs a declarative configuration of the TargetStatus type for use with
// apply.
func TargetStatus() *TargetStatusApplyConfiguration {
	return &TargetStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TargetStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TargetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithJobRef sets the JobRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobRef field is set to the value of the last call.
func (b *TargetStatusApplyConfiguration) WithJobRef(value corev1.ObjectReference) *TargetStatusApplyConfiguration {
	b.JobRef = &value
	return b
}

// WithConfigSecretRef sets the ConfigSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigSecretRef field is set to the value of the last call.
func (b *TargetStatusApplyConfiguration) WithConfigSecretRef(value corev1.ObjectReference) *TargetStatusApplyConfiguration {
	b.ConfigSecretRef = &value
	return b
}
