// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// TargetSpecApplyConfiguration represents a declarative configuration of the TargetSpec type for use
// with apply.
type TargetSpecApplyConfiguration struct {
	Releases map[string]v1.LocalObjectReference `json:"releases,omitempty"`
	Userdata *runtime.RawExtension              `json:"userdata,omitempty"`
}

// TargetSpecApplyConfiguration constructs a declarative configuration of the TargetSpec type for use with
// apply.
func TargetSpec() *TargetSpecApplyConfiguration {
	return &TargetSpecApplyConfiguration{}
}

// WithReleases puts the entries into the Releases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Releases field,
// overwriting an existing map entries in Releases field with the same key.
func (b *TargetSpecApplyConfiguration) WithReleases(entries map[string]v1.LocalObjectReference) *TargetSpecApplyConfiguration {
	if b.Releases == nil && len(entries) > 0 {
		b.Releases = make(map[string]v1.LocalObjectReference, len(entries))
	}
	for k, v := range entries {
		b.Releases[k] = v
	}
	return b
}

// WithUserdata sets the Userdata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Userdata field is set to the value of the last call.
func (b *TargetSpecApplyConfiguration) WithUserdata(value runtime.RawExtension) *TargetSpecApplyConfiguration {
	b.Userdata = &value
	return b
}
