// Copyright BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TargetReportSpecApplyConfiguration represents a declarative configuration of the TargetReportSpec type for use
// with apply.
//
// TargetReportSpec is one target cluster's state as observed by its agent.
// It is a full snapshot, never append-only: written exclusively by the agent,
// read exclusively by the targetreport controller.
type TargetReportSpecApplyConfiguration struct {
	// LastReportTime is set by the agent at publish time. The agent owns it, and
	// it must advance on every update.
	LastReportTime *v1.Time `json:"lastReportTime,omitempty"`
	// Releases are the OCIRepository/HelmRelease pairs the agent observed:
	// a snapshot of what is currently deployed. Observational only — it never
	// gates anything.
	Releases []ReleaseReportApplyConfiguration `json:"releases,omitempty"`
	// Preflight holds the agent's health-check results that gate new releases:
	// failed checks block deploying to this target. Unlike Releases, it says
	// nothing about what is currently deployed.
	Preflight *PreflightReportApplyConfiguration `json:"preflight,omitempty"`
}

// TargetReportSpecApplyConfiguration constructs a declarative configuration of the TargetReportSpec type for use with
// apply.
func TargetReportSpec() *TargetReportSpecApplyConfiguration {
	return &TargetReportSpecApplyConfiguration{}
}

// WithLastReportTime sets the LastReportTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastReportTime field is set to the value of the last call.
func (b *TargetReportSpecApplyConfiguration) WithLastReportTime(value v1.Time) *TargetReportSpecApplyConfiguration {
	b.LastReportTime = &value
	return b
}

// WithReleases adds the given value to the Releases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Releases field.
func (b *TargetReportSpecApplyConfiguration) WithReleases(values ...*ReleaseReportApplyConfiguration) *TargetReportSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReleases")
		}
		b.Releases = append(b.Releases, *values[i])
	}
	return b
}

// WithPreflight sets the Preflight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Preflight field is set to the value of the last call.
func (b *TargetReportSpecApplyConfiguration) WithPreflight(value *PreflightReportApplyConfiguration) *TargetReportSpecApplyConfiguration {
	b.Preflight = value
	return b
}
