// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// TargetSpecApplyConfiguration represents a declarative configuration of the TargetSpec type for use
// with apply.
//
// TargetSpec defines the desired state of a Target.
// It specifies the render registry and configuration for this deployment target.
type TargetSpecApplyConfiguration struct {
	// RenderRegistryRef references the Registry to push rendered desired state to.
	// The referenced Registry must have SolarSecretRef set for rendering to succeed.
	// When Namespace is set, the Registry resides in a different namespace than this
	// Target; cross-namespace references require a ReferenceGrant in the Registry's
	// namespace that grants access to this Target's namespace.
	RenderRegistryRef *ObjectReferenceApplyConfiguration `json:"renderRegistryRef,omitempty"`
	// Userdata contains arbitrary custom data or configuration specific to this target.
	// This enables target-specific customization and deployment parameters.
	Userdata *runtime.RawExtension `json:"userdata,omitempty"`
}

// TargetSpecApplyConfiguration constructs a declarative configuration of the TargetSpec type for use with
// apply.
func TargetSpec() *TargetSpecApplyConfiguration {
	return &TargetSpecApplyConfiguration{}
}

// WithRenderRegistryRef sets the RenderRegistryRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenderRegistryRef field is set to the value of the last call.
func (b *TargetSpecApplyConfiguration) WithRenderRegistryRef(value *ObjectReferenceApplyConfiguration) *TargetSpecApplyConfiguration {
	b.RenderRegistryRef = value
	return b
}

// WithUserdata sets the Userdata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Userdata field is set to the value of the last call.
func (b *TargetSpecApplyConfiguration) WithUserdata(value runtime.RawExtension) *TargetSpecApplyConfiguration {
	b.Userdata = &value
	return b
}
