// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ValidationCheckApplyConfiguration represents a declarative configuration of the ValidationCheck type for use
// with apply.
type ValidationCheckApplyConfiguration struct {
	Name      *string  `json:"name,omitempty"`
	Passed    *bool    `json:"passed,omitempty"`
	Message   *string  `json:"message,omitempty"`
	Timestamp *v1.Time `json:"timestamp,omitempty"`
}

// ValidationCheckApplyConfiguration constructs a declarative configuration of the ValidationCheck type for use with
// apply.
func ValidationCheck() *ValidationCheckApplyConfiguration {
	return &ValidationCheckApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ValidationCheckApplyConfiguration) WithName(value string) *ValidationCheckApplyConfiguration {
	b.Name = &value
	return b
}

// WithPassed sets the Passed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Passed field is set to the value of the last call.
func (b *ValidationCheckApplyConfiguration) WithPassed(value bool) *ValidationCheckApplyConfiguration {
	b.Passed = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ValidationCheckApplyConfiguration) WithMessage(value string) *ValidationCheckApplyConfiguration {
	b.Message = &value
	return b
}

// WithTimestamp sets the Timestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timestamp field is set to the value of the last call.
func (b *ValidationCheckApplyConfiguration) WithTimestamp(value v1.Time) *ValidationCheckApplyConfiguration {
	b.Timestamp = &value
	return b
}
