// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// WebhookAuthApplyConfiguration represents a declarative configuration of the WebhookAuth type for use
// with apply.
type WebhookAuthApplyConfiguration struct {
	Type      *string                  `json:"type,omitempty"`
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// WebhookAuthApplyConfiguration constructs a declarative configuration of the WebhookAuth type for use with
// apply.
func WebhookAuth() *WebhookAuthApplyConfiguration {
	return &WebhookAuthApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *WebhookAuthApplyConfiguration) WithType(value string) *WebhookAuthApplyConfiguration {
	b.Type = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *WebhookAuthApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *WebhookAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}
