// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// WebhookApplyConfiguration represents a declarative configuration of the Webhook type for use
// with apply.
type WebhookApplyConfiguration struct {
	Flavor             *string                  `json:"flavor,omitempty"`
	Path               *string                  `json:"path,omitempty"`
	AuthTokenSecretRef *v1.LocalObjectReference `json:"authTokenSecretRef,omitempty"`
}

// WebhookApplyConfiguration constructs a declarative configuration of the Webhook type for use with
// apply.
func Webhook() *WebhookApplyConfiguration {
	return &WebhookApplyConfiguration{}
}

// WithFlavor sets the Flavor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Flavor field is set to the value of the last call.
func (b *WebhookApplyConfiguration) WithFlavor(value string) *WebhookApplyConfiguration {
	b.Flavor = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *WebhookApplyConfiguration) WithPath(value string) *WebhookApplyConfiguration {
	b.Path = &value
	return b
}

// WithAuthTokenSecretRef sets the AuthTokenSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthTokenSecretRef field is set to the value of the last call.
func (b *WebhookApplyConfiguration) WithAuthTokenSecretRef(value v1.LocalObjectReference) *WebhookApplyConfiguration {
	b.AuthTokenSecretRef = &value
	return b
}
