{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "solar-discovery.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "solar-discovery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "solar-discovery.selectorLabels" . | nindent 4 }}
{{- end }}
