rules:
  - apiGroups:
      - solar.opendefense.cloud
    resources:
      - components
      - componentversions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - solar.opendefense.cloud
    resources:
      - registries
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
