// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BootstrapsGetter has a method to return a BootstrapInterface.
// A group's client should implement this interface.
type BootstrapsGetter interface {
	Bootstraps(namespace string) BootstrapInterface
}

// BootstrapInterface has methods to work with Bootstrap resources.
type BootstrapInterface interface {
	Create(ctx context.Context, bootstrap *solarv1alpha1.Bootstrap, opts v1.CreateOptions) (*solarv1alpha1.Bootstrap, error)
	Update(ctx context.Context, bootstrap *solarv1alpha1.Bootstrap, opts v1.UpdateOptions) (*solarv1alpha1.Bootstrap, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bootstrap *solarv1alpha1.Bootstrap, opts v1.UpdateOptions) (*solarv1alpha1.Bootstrap, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.Bootstrap, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.BootstrapList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.Bootstrap, err error)
	Apply(ctx context.Context, bootstrap *applyconfigurationssolarv1alpha1.BootstrapApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Bootstrap, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, bootstrap *applyconfigurationssolarv1alpha1.BootstrapApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Bootstrap, err error)
	BootstrapExpansion
}

// bootstraps implements BootstrapInterface
type bootstraps struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.Bootstrap, *solarv1alpha1.BootstrapList, *applyconfigurationssolarv1alpha1.BootstrapApplyConfiguration]
}

// newBootstraps returns a Bootstraps
func newBootstraps(c *SolarV1alpha1Client, namespace string) *bootstraps {
	return &bootstraps{
		gentype.NewClientWithListAndApply[*solarv1alpha1.Bootstrap, *solarv1alpha1.BootstrapList, *applyconfigurationssolarv1alpha1.BootstrapApplyConfiguration](
			"bootstraps",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.Bootstrap { return &solarv1alpha1.Bootstrap{} },
			func() *solarv1alpha1.BootstrapList { return &solarv1alpha1.BootstrapList{} },
		),
	}
}
