// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ComponentVersionsGetter has a method to return a ComponentVersionInterface.
// A group's client should implement this interface.
type ComponentVersionsGetter interface {
	ComponentVersions(namespace string) ComponentVersionInterface
}

// ComponentVersionInterface has methods to work with ComponentVersion resources.
type ComponentVersionInterface interface {
	Create(ctx context.Context, componentVersion *solarv1alpha1.ComponentVersion, opts v1.CreateOptions) (*solarv1alpha1.ComponentVersion, error)
	Update(ctx context.Context, componentVersion *solarv1alpha1.ComponentVersion, opts v1.UpdateOptions) (*solarv1alpha1.ComponentVersion, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, componentVersion *solarv1alpha1.ComponentVersion, opts v1.UpdateOptions) (*solarv1alpha1.ComponentVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.ComponentVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.ComponentVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.ComponentVersion, err error)
	Apply(ctx context.Context, componentVersion *applyconfigurationssolarv1alpha1.ComponentVersionApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.ComponentVersion, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, componentVersion *applyconfigurationssolarv1alpha1.ComponentVersionApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.ComponentVersion, err error)
	ComponentVersionExpansion
}

// componentVersions implements ComponentVersionInterface
type componentVersions struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.ComponentVersion, *solarv1alpha1.ComponentVersionList, *applyconfigurationssolarv1alpha1.ComponentVersionApplyConfiguration]
}

// newComponentVersions returns a ComponentVersions
func newComponentVersions(c *SolarV1alpha1Client, namespace string) *componentVersions {
	return &componentVersions{
		gentype.NewClientWithListAndApply[*solarv1alpha1.ComponentVersion, *solarv1alpha1.ComponentVersionList, *applyconfigurationssolarv1alpha1.ComponentVersionApplyConfiguration](
			"componentversions",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.ComponentVersion { return &solarv1alpha1.ComponentVersion{} },
			func() *solarv1alpha1.ComponentVersionList { return &solarv1alpha1.ComponentVersionList{} },
		),
	}
}
