// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ComponentsGetter has a method to return a ComponentInterface.
// A group's client should implement this interface.
type ComponentsGetter interface {
	Components(namespace string) ComponentInterface
}

// ComponentInterface has methods to work with Component resources.
type ComponentInterface interface {
	Create(ctx context.Context, component *solarv1alpha1.Component, opts v1.CreateOptions) (*solarv1alpha1.Component, error)
	Update(ctx context.Context, component *solarv1alpha1.Component, opts v1.UpdateOptions) (*solarv1alpha1.Component, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, component *solarv1alpha1.Component, opts v1.UpdateOptions) (*solarv1alpha1.Component, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.Component, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.ComponentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.Component, err error)
	Apply(ctx context.Context, component *applyconfigurationssolarv1alpha1.ComponentApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Component, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, component *applyconfigurationssolarv1alpha1.ComponentApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Component, err error)
	ComponentExpansion
}

// components implements ComponentInterface
type components struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.Component, *solarv1alpha1.ComponentList, *applyconfigurationssolarv1alpha1.ComponentApplyConfiguration]
}

// newComponents returns a Components
func newComponents(c *SolarV1alpha1Client, namespace string) *components {
	return &components{
		gentype.NewClientWithListAndApply[*solarv1alpha1.Component, *solarv1alpha1.ComponentList, *applyconfigurationssolarv1alpha1.ComponentApplyConfiguration](
			"components",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.Component { return &solarv1alpha1.Component{} },
			func() *solarv1alpha1.ComponentList { return &solarv1alpha1.ComponentList{} },
		),
	}
}
