// Copyright 2025 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DiscoveriesGetter has a method to return a DiscoveryInterface.
// A group's client should implement this interface.
type DiscoveriesGetter interface {
	Discoveries(namespace string) DiscoveryInterface
}

// DiscoveryInterface has methods to work with Discovery resources.
type DiscoveryInterface interface {
	Create(ctx context.Context, discovery *solarv1alpha1.Discovery, opts v1.CreateOptions) (*solarv1alpha1.Discovery, error)
	Update(ctx context.Context, discovery *solarv1alpha1.Discovery, opts v1.UpdateOptions) (*solarv1alpha1.Discovery, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, discovery *solarv1alpha1.Discovery, opts v1.UpdateOptions) (*solarv1alpha1.Discovery, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.Discovery, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.DiscoveryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.Discovery, err error)
	Apply(ctx context.Context, discovery *applyconfigurationssolarv1alpha1.DiscoveryApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Discovery, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, discovery *applyconfigurationssolarv1alpha1.DiscoveryApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Discovery, err error)
	DiscoveryExpansion
}

// discoveries implements DiscoveryInterface
type discoveries struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.Discovery, *solarv1alpha1.DiscoveryList, *applyconfigurationssolarv1alpha1.DiscoveryApplyConfiguration]
}

// newDiscoveries returns a Discoveries
func newDiscoveries(c *SolarV1alpha1Client, namespace string) *discoveries {
	return &discoveries{
		gentype.NewClientWithListAndApply[*solarv1alpha1.Discovery, *solarv1alpha1.DiscoveryList, *applyconfigurationssolarv1alpha1.DiscoveryApplyConfiguration](
			"discoveries",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.Discovery { return &solarv1alpha1.Discovery{} },
			func() *solarv1alpha1.DiscoveryList { return &solarv1alpha1.DiscoveryList{} },
		),
	}
}
