// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type BootstrapExpansion interface{}

type ComponentExpansion interface{}

type ComponentVersionExpansion interface{}

type DiscoveryExpansion interface{}

type ProfileExpansion interface{}

type ReleaseExpansion interface{}

type RenderTaskExpansion interface{}

type TargetExpansion interface{}
