// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ComponentExpansion interface{}

type ComponentVersionExpansion interface{}

type ProfileExpansion interface{}

type ReferenceGrantExpansion interface{}

type RegistryExpansion interface{}

type RegistryBindingExpansion interface{}

type ReleaseExpansion interface{}

type ReleaseBindingExpansion interface{}

type RenderTaskExpansion interface{}

type TargetExpansion interface{}
