// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProfilesGetter has a method to return a ProfileInterface.
// A group's client should implement this interface.
type ProfilesGetter interface {
	Profiles(namespace string) ProfileInterface
}

// ProfileInterface has methods to work with Profile resources.
type ProfileInterface interface {
	Create(ctx context.Context, profile *solarv1alpha1.Profile, opts v1.CreateOptions) (*solarv1alpha1.Profile, error)
	Update(ctx context.Context, profile *solarv1alpha1.Profile, opts v1.UpdateOptions) (*solarv1alpha1.Profile, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, profile *solarv1alpha1.Profile, opts v1.UpdateOptions) (*solarv1alpha1.Profile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.Profile, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.ProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.Profile, err error)
	Apply(ctx context.Context, profile *applyconfigurationssolarv1alpha1.ProfileApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Profile, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, profile *applyconfigurationssolarv1alpha1.ProfileApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Profile, err error)
	ProfileExpansion
}

// profiles implements ProfileInterface
type profiles struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.Profile, *solarv1alpha1.ProfileList, *applyconfigurationssolarv1alpha1.ProfileApplyConfiguration]
}

// newProfiles returns a Profiles
func newProfiles(c *SolarV1alpha1Client, namespace string) *profiles {
	return &profiles{
		gentype.NewClientWithListAndApply[*solarv1alpha1.Profile, *solarv1alpha1.ProfileList, *applyconfigurationssolarv1alpha1.ProfileApplyConfiguration](
			"profiles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.Profile { return &solarv1alpha1.Profile{} },
			func() *solarv1alpha1.ProfileList { return &solarv1alpha1.ProfileList{} },
		),
	}
}
