// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ReleaseBindingsGetter has a method to return a ReleaseBindingInterface.
// A group's client should implement this interface.
type ReleaseBindingsGetter interface {
	ReleaseBindings(namespace string) ReleaseBindingInterface
}

// ReleaseBindingInterface has methods to work with ReleaseBinding resources.
type ReleaseBindingInterface interface {
	Create(ctx context.Context, releaseBinding *solarv1alpha1.ReleaseBinding, opts v1.CreateOptions) (*solarv1alpha1.ReleaseBinding, error)
	Update(ctx context.Context, releaseBinding *solarv1alpha1.ReleaseBinding, opts v1.UpdateOptions) (*solarv1alpha1.ReleaseBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, releaseBinding *solarv1alpha1.ReleaseBinding, opts v1.UpdateOptions) (*solarv1alpha1.ReleaseBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.ReleaseBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.ReleaseBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.ReleaseBinding, err error)
	Apply(ctx context.Context, releaseBinding *applyconfigurationssolarv1alpha1.ReleaseBindingApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.ReleaseBinding, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, releaseBinding *applyconfigurationssolarv1alpha1.ReleaseBindingApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.ReleaseBinding, err error)
	ReleaseBindingExpansion
}

// releaseBindings implements ReleaseBindingInterface
type releaseBindings struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.ReleaseBinding, *solarv1alpha1.ReleaseBindingList, *applyconfigurationssolarv1alpha1.ReleaseBindingApplyConfiguration]
}

// newReleaseBindings returns a ReleaseBindings
func newReleaseBindings(c *SolarV1alpha1Client, namespace string) *releaseBindings {
	return &releaseBindings{
		gentype.NewClientWithListAndApply[*solarv1alpha1.ReleaseBinding, *solarv1alpha1.ReleaseBindingList, *applyconfigurationssolarv1alpha1.ReleaseBindingApplyConfiguration](
			"releasebindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.ReleaseBinding { return &solarv1alpha1.ReleaseBinding{} },
			func() *solarv1alpha1.ReleaseBindingList { return &solarv1alpha1.ReleaseBindingList{} },
		),
	}
}
