// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ReleasesGetter has a method to return a ReleaseInterface.
// A group's client should implement this interface.
type ReleasesGetter interface {
	Releases(namespace string) ReleaseInterface
}

// ReleaseInterface has methods to work with Release resources.
type ReleaseInterface interface {
	Create(ctx context.Context, release *solarv1alpha1.Release, opts v1.CreateOptions) (*solarv1alpha1.Release, error)
	Update(ctx context.Context, release *solarv1alpha1.Release, opts v1.UpdateOptions) (*solarv1alpha1.Release, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, release *solarv1alpha1.Release, opts v1.UpdateOptions) (*solarv1alpha1.Release, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.Release, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.ReleaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.Release, err error)
	Apply(ctx context.Context, release *applyconfigurationssolarv1alpha1.ReleaseApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Release, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, release *applyconfigurationssolarv1alpha1.ReleaseApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.Release, err error)
	ReleaseExpansion
}

// releases implements ReleaseInterface
type releases struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.Release, *solarv1alpha1.ReleaseList, *applyconfigurationssolarv1alpha1.ReleaseApplyConfiguration]
}

// newReleases returns a Releases
func newReleases(c *SolarV1alpha1Client, namespace string) *releases {
	return &releases{
		gentype.NewClientWithListAndApply[*solarv1alpha1.Release, *solarv1alpha1.ReleaseList, *applyconfigurationssolarv1alpha1.ReleaseApplyConfiguration](
			"releases",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.Release { return &solarv1alpha1.Release{} },
			func() *solarv1alpha1.ReleaseList { return &solarv1alpha1.ReleaseList{} },
		),
	}
}
