// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	solarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	applyconfigurationssolarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	scheme "go.opendefense.cloud/solar/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RenderArtifactsGetter has a method to return a RenderArtifactInterface.
// A group's client should implement this interface.
type RenderArtifactsGetter interface {
	RenderArtifacts(namespace string) RenderArtifactInterface
}

// RenderArtifactInterface has methods to work with RenderArtifact resources.
type RenderArtifactInterface interface {
	Create(ctx context.Context, renderArtifact *solarv1alpha1.RenderArtifact, opts v1.CreateOptions) (*solarv1alpha1.RenderArtifact, error)
	Update(ctx context.Context, renderArtifact *solarv1alpha1.RenderArtifact, opts v1.UpdateOptions) (*solarv1alpha1.RenderArtifact, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, renderArtifact *solarv1alpha1.RenderArtifact, opts v1.UpdateOptions) (*solarv1alpha1.RenderArtifact, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*solarv1alpha1.RenderArtifact, error)
	List(ctx context.Context, opts v1.ListOptions) (*solarv1alpha1.RenderArtifactList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *solarv1alpha1.RenderArtifact, err error)
	Apply(ctx context.Context, renderArtifact *applyconfigurationssolarv1alpha1.RenderArtifactApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.RenderArtifact, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, renderArtifact *applyconfigurationssolarv1alpha1.RenderArtifactApplyConfiguration, opts v1.ApplyOptions) (result *solarv1alpha1.RenderArtifact, err error)
	RenderArtifactExpansion
}

// renderArtifacts implements RenderArtifactInterface
type renderArtifacts struct {
	*gentype.ClientWithListAndApply[*solarv1alpha1.RenderArtifact, *solarv1alpha1.RenderArtifactList, *applyconfigurationssolarv1alpha1.RenderArtifactApplyConfiguration]
}

// newRenderArtifacts returns a RenderArtifacts
func newRenderArtifacts(c *SolarV1alpha1Client, namespace string) *renderArtifacts {
	return &renderArtifacts{
		gentype.NewClientWithListAndApply[*solarv1alpha1.RenderArtifact, *solarv1alpha1.RenderArtifactList, *applyconfigurationssolarv1alpha1.RenderArtifactApplyConfiguration](
			"renderartifacts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *solarv1alpha1.RenderArtifact { return &solarv1alpha1.RenderArtifact{} },
			func() *solarv1alpha1.RenderArtifactList { return &solarv1alpha1.RenderArtifactList{} },
		),
	}
}
