{{- range $k, $v := .Values.releases }}

{{- $name := printf "%s-%s" $.Release.Name $k }}

{{- if gt (len $name) 53 }}
  {{- $sha := $name | sha256sum | trunc 10 }}
  {{- $name = printf "%s-%s" ($name | trunc 42) $sha }}
{{- end }}

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  interval: 10m
  url: oci://{{ $v.repository }}
  {{- if $v.insecure }}
  insecure: true
  {{- end }}
  # FIXME: replace hardcoded secret with outcome of #165
  secretRef:
    name: regcred
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    semver: {{ $v.tag }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: {{ $name }}
  releaseName: {{ $name }}
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    userdata: # comes directly from Target
      {{- with $.Values.userdata }}
        {{ . | toYaml | nindent 6 }}
      {{- end }}
{{- end }}
