// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "go.opendefense.cloud/solar/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Components returns a ComponentInformer.
	Components() ComponentInformer
	// ComponentVersions returns a ComponentVersionInformer.
	ComponentVersions() ComponentVersionInformer
	// Profiles returns a ProfileInformer.
	Profiles() ProfileInformer
	// ReferenceGrants returns a ReferenceGrantInformer.
	ReferenceGrants() ReferenceGrantInformer
	// Registries returns a RegistryInformer.
	Registries() RegistryInformer
	// RegistryBindings returns a RegistryBindingInformer.
	RegistryBindings() RegistryBindingInformer
	// Releases returns a ReleaseInformer.
	Releases() ReleaseInformer
	// ReleaseBindings returns a ReleaseBindingInformer.
	ReleaseBindings() ReleaseBindingInformer
	// RenderTasks returns a RenderTaskInformer.
	RenderTasks() RenderTaskInformer
	// Targets returns a TargetInformer.
	Targets() TargetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Components returns a ComponentInformer.
func (v *version) Components() ComponentInformer {
	return &componentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ComponentVersions returns a ComponentVersionInformer.
func (v *version) ComponentVersions() ComponentVersionInformer {
	return &componentVersionInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Profiles returns a ProfileInformer.
func (v *version) Profiles() ProfileInformer {
	return &profileInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ReferenceGrants returns a ReferenceGrantInformer.
func (v *version) ReferenceGrants() ReferenceGrantInformer {
	return &referenceGrantInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Registries returns a RegistryInformer.
func (v *version) Registries() RegistryInformer {
	return &registryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RegistryBindings returns a RegistryBindingInformer.
func (v *version) RegistryBindings() RegistryBindingInformer {
	return &registryBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Releases returns a ReleaseInformer.
func (v *version) Releases() ReleaseInformer {
	return &releaseInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ReleaseBindings returns a ReleaseBindingInformer.
func (v *version) ReleaseBindings() ReleaseBindingInformer {
	return &releaseBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RenderTasks returns a RenderTaskInformer.
func (v *version) RenderTasks() RenderTaskInformer {
	return &renderTaskInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Targets returns a TargetInformer.
func (v *version) Targets() TargetInformer {
	return &targetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
