// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisolarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	versioned "go.opendefense.cloud/solar/client-go/clientset/versioned"
	internalinterfaces "go.opendefense.cloud/solar/client-go/informers/externalversions/internalinterfaces"
	solarv1alpha1 "go.opendefense.cloud/solar/client-go/listers/solar/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TargetInformer provides access to a shared informer and lister for
// Targets.
type TargetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() solarv1alpha1.TargetLister
}

type targetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTargetInformer constructs a new informer for Target type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTargetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTargetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTargetInformer constructs a new informer for Target type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTargetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SolarV1alpha1().Targets(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SolarV1alpha1().Targets(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SolarV1alpha1().Targets(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SolarV1alpha1().Targets(namespace).Watch(ctx, options)
			},
		}, client),
		&apisolarv1alpha1.Target{},
		resyncPeriod,
		indexers,
	)
}

func (f *targetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTargetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *targetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisolarv1alpha1.Target{}, f.defaultInformer)
}

func (f *targetInformer) Lister() solarv1alpha1.TargetLister {
	return solarv1alpha1.NewTargetLister(f.Informer().GetIndexer())
}
