// Copyright BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisolarv1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	versioned "go.opendefense.cloud/solar/client-go/clientset/versioned"
	internalinterfaces "go.opendefense.cloud/solar/client-go/informers/externalversions/internalinterfaces"
	solarv1alpha1 "go.opendefense.cloud/solar/client-go/listers/solar/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TargetReportInformer provides access to a shared informer and lister for
// TargetReports. Prefer using the type-safe variant (see [TypedTargetReportInformer]).
type TargetReportInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() solarv1alpha1.TargetReportLister
}

// TypedTargetReportInformer provides access to a shared informer and lister for
// TargetReports, including the type-safe TypedInformer variant.
// It is a superset of TargetReportInformer.
type TypedTargetReportInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() TargetReportIndexInformer
	Lister() solarv1alpha1.TargetReportLister
}

// TargetReportIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type TargetReportIndexInformer cache.TypedSharedIndexInformer[*apisolarv1alpha1.TargetReport]

// TargetReportHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for TargetReport.
type TargetReportHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisolarv1alpha1.TargetReport]

// TargetReportDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for TargetReport.
type TargetReportDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisolarv1alpha1.TargetReport]

// TargetReportFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for TargetReport.
type TargetReportFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisolarv1alpha1.TargetReport]

// TargetReportIndexers is a specialization of [cache.TypedIndexers] for TargetReport.
type TargetReportIndexers = cache.TypedIndexers[*apisolarv1alpha1.TargetReport]

// DeletedTargetReport is a specialization of [cache.DeletedObject] for TargetReport.
type DeletedTargetReport = cache.DeletedObject[*apisolarv1alpha1.TargetReport]

type targetReportInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTargetReportInformer constructs a new informer for TargetReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTargetReportInformer]).
func NewTargetReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewTargetReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedTargetReportInformer constructs a new informer for TargetReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTargetReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TargetReportIndexers) TargetReportIndexInformer {
	return NewTypedTargetReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredTargetReportInformer constructs a new informer for TargetReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredTargetReportInformer]).
func NewFilteredTargetReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedTargetReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredTargetReportInformer constructs a new informer for TargetReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredTargetReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers TargetReportIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) TargetReportIndexInformer {
	return NewTypedTargetReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewTargetReportInformerWithOptions constructs a new informer for TargetReport type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTargetReportInformerWithOptions]).
func NewTargetReportInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedTargetReportInformerWithOptions(client, namespace, options)
}

// NewTypedTargetReportInformerWithOptions constructs a new informer for TargetReport type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTargetReportInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) TargetReportIndexInformer {
	gvr := schema.GroupVersionResource{Group: "solar.opendefense.cloud", Version: "v1alpha1", Resource: "targetreports"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisolarv1alpha1.TargetReport](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SolarV1alpha1().TargetReports(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SolarV1alpha1().TargetReports(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SolarV1alpha1().TargetReports(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SolarV1alpha1().TargetReports(namespace).Watch(ctx, opts)
			},
		}, client),
		&apisolarv1alpha1.TargetReport{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *targetReportInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedTargetReportInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *targetReportInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *targetReportInformer) TypedInformer() TargetReportIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisolarv1alpha1.TargetReport](f.factory.InformerFor(&apisolarv1alpha1.TargetReport{}, f.defaultInformer))
}

func (f *targetReportInformer) Lister() solarv1alpha1.TargetReportLister {
	return solarv1alpha1.NewTargetReportLister(f.Informer().GetIndexer())
}

// ToTypedTargetReportInformer converts an untyped informer into a TypedTargetReportInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TargetReport. If that is not the case, calling type-safe methods of the returned
// TypedTargetReportInformer leads to runtime panics. A safer alternative is to pass
// around a TypedTargetReportInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedTargetReportInformer(informer TargetReportInformer) TypedTargetReportInformer {
	if informer, ok := informer.(TypedTargetReportInformer); ok {
		return informer
	}
	return &targetReportTypedInformerAdapter{informer}
}

type targetReportTypedInformerAdapter struct {
	TargetReportInformer
}

func (a *targetReportTypedInformerAdapter) TypedInformer() TargetReportIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisolarv1alpha1.TargetReport](a.Informer())
}

// ToTargetReportIndexInformer converts an untyped informer into a TargetReportIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *TargetReport. If that is not the case, calling type-safe methods of the returned
// TargetReportIndexInformer leads to runtime panics. A safer alternative is to pass
// around a TargetReportIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToTargetReportIndexInformer(informer cache.SharedIndexInformer) TargetReportIndexInformer {
	if informer, ok := informer.(TargetReportIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisolarv1alpha1.TargetReport](informer)
}
