{{- if and .Values.apiserverKubeconfig.value (not .Values.apiserverKubeconfig.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solar-agent.apiserverKubeconfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "solar-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.apiserverKubeconfig.key }}: {{ .Values.apiserverKubeconfig.value | b64enc | quote }}
{{- end }}
