apiVersion: v2
name: solar-agent
description: Helm chart for SOLAR Agent
type: application
version: 0.1.0
appVersion: "latest"
home: https://solar.opendefense.cloud
sources:
  - https://github.com/opendefensecloud/solution-arsenal
maintainers:
  - name: ODD Team
    email: odd@opendefense.cloud
keywords:
  - agent
  - fluxcd
  - status
  - reporting
  - kubernetes
