nav:
- Home: index.md
- Getting Started:
  - getting-started.md
  - Walk Through:
    - walk-through/about.md
    - walk-through/*.md
- User Guide:
  - user-guide/*.md
- Operator Manual:
  - Installation:
    - operator-manual/installation/installation.md
    - operator-manual/installation/*.md
  - operator-manual/*.md
- Developer Guide:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - developer-guide/architecture.md
  - Controller Documentation:
    - Discovery Controller: developer-guide/discovery_controller.md
    - Target Controller: developer-guide/target_controller.md
    - Release Controller: developer-guide/release_controller.md
    - Bootstrap Controller: developer-guide/bootstrap_controller.md
    - RenderTask Controller: developer-guide/rendertask_controller.md
  - ADRs:
    - developer-guide/adrs/*.md
