nav:
- Home: index.md
- Getting Started:
  - getting-started.md
  - Walk Through:
    - walk-through/index.md
    - walk-through/*.md
- User Guide:
  - user-guide/*.md
- Operator Manual:
  - Installation:
    - operator-manual/installation/installation.md
    - operator-manual/installation/*.md
  - operator-manual/*.md
- Developer Guide:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - developer-guide/architecture.md
  - developer-guide/rendering-pipeline.md
  - developer-guide/dev-cluster-with-kind.md
  - developer-guide/working-with-docs.md
  - Discovery:
    - developer-guide/discovery_pipeline.md
  - Controllers:
    - developer-guide/release_controller.md
    - developer-guide/profile_controller.md
    - developer-guide/target_controller.md
    - developer-guide/rendertask_controller.md
  - ADRs:
    - developer-guide/adrs/*.md
