//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	solar "go.opendefense.cloud/solar/api/solar"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CatalogItem)(nil), (*solar.CatalogItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItem_To_solar_CatalogItem(a.(*CatalogItem), b.(*solar.CatalogItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItem)(nil), (*CatalogItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItem_To_v1alpha1_CatalogItem(a.(*solar.CatalogItem), b.(*CatalogItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemList)(nil), (*solar.CatalogItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(a.(*CatalogItemList), b.(*solar.CatalogItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemList)(nil), (*CatalogItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(a.(*solar.CatalogItemList), b.(*CatalogItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemSpec)(nil), (*solar.CatalogItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(a.(*CatalogItemSpec), b.(*solar.CatalogItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemSpec)(nil), (*CatalogItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(a.(*solar.CatalogItemSpec), b.(*CatalogItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemStatus)(nil), (*solar.CatalogItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(a.(*CatalogItemStatus), b.(*solar.CatalogItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemStatus)(nil), (*CatalogItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(a.(*solar.CatalogItemStatus), b.(*CatalogItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemVersionSpec)(nil), (*solar.CatalogItemVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(a.(*CatalogItemVersionSpec), b.(*solar.CatalogItemVersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemVersionSpec)(nil), (*CatalogItemVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(a.(*solar.CatalogItemVersionSpec), b.(*CatalogItemVersionSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CatalogItem_To_solar_CatalogItem(in *CatalogItem, out *solar.CatalogItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CatalogItem_To_solar_CatalogItem is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItem_To_solar_CatalogItem(in *CatalogItem, out *solar.CatalogItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItem_To_solar_CatalogItem(in, out, s)
}

func autoConvert_solar_CatalogItem_To_v1alpha1_CatalogItem(in *solar.CatalogItem, out *CatalogItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_solar_CatalogItem_To_v1alpha1_CatalogItem is an autogenerated conversion function.
func Convert_solar_CatalogItem_To_v1alpha1_CatalogItem(in *solar.CatalogItem, out *CatalogItem, s conversion.Scope) error {
	return autoConvert_solar_CatalogItem_To_v1alpha1_CatalogItem(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(in *CatalogItemList, out *solar.CatalogItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]solar.CatalogItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_CatalogItemList_To_solar_CatalogItemList is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(in *CatalogItemList, out *solar.CatalogItemList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(in, out, s)
}

func autoConvert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(in *solar.CatalogItemList, out *CatalogItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CatalogItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_solar_CatalogItemList_To_v1alpha1_CatalogItemList is an autogenerated conversion function.
func Convert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(in *solar.CatalogItemList, out *CatalogItemList, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(in *CatalogItemSpec, out *solar.CatalogItemSpec, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Versions = *(*[]solar.CatalogItemVersionSpec)(unsafe.Pointer(&in.Versions))
	out.Provider = in.Provider
	out.CreationTime = in.CreationTime
	return nil
}

// Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(in *CatalogItemSpec, out *solar.CatalogItemSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(in, out, s)
}

func autoConvert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(in *solar.CatalogItemSpec, out *CatalogItemSpec, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Versions = *(*[]CatalogItemVersionSpec)(unsafe.Pointer(&in.Versions))
	out.Provider = in.Provider
	out.CreationTime = in.CreationTime
	return nil
}

// Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec is an autogenerated conversion function.
func Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(in *solar.CatalogItemSpec, out *CatalogItemSpec, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(in *CatalogItemStatus, out *solar.CatalogItemStatus, s conversion.Scope) error {
	out.LastDiscoveredAt = (*v1.Time)(unsafe.Pointer(in.LastDiscoveredAt))
	return nil
}

// Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(in *CatalogItemStatus, out *solar.CatalogItemStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(in, out, s)
}

func autoConvert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(in *solar.CatalogItemStatus, out *CatalogItemStatus, s conversion.Scope) error {
	out.LastDiscoveredAt = (*v1.Time)(unsafe.Pointer(in.LastDiscoveredAt))
	return nil
}

// Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus is an autogenerated conversion function.
func Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(in *solar.CatalogItemStatus, out *CatalogItemStatus, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(in *CatalogItemVersionSpec, out *solar.CatalogItemVersionSpec, s conversion.Scope) error {
	out.Version = in.Version
	out.Digest = in.Digest
	return nil
}

// Convert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(in *CatalogItemVersionSpec, out *solar.CatalogItemVersionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(in, out, s)
}

func autoConvert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(in *solar.CatalogItemVersionSpec, out *CatalogItemVersionSpec, s conversion.Scope) error {
	out.Version = in.Version
	out.Digest = in.Digest
	return nil
}

// Convert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec is an autogenerated conversion function.
func Convert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(in *solar.CatalogItemVersionSpec, out *CatalogItemVersionSpec, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(in, out, s)
}
