//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Component) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Component"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ComponentList) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ComponentList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ComponentSpec) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ComponentSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ComponentStatus) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ComponentStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ComponentVersion) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ComponentVersion"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ComponentVersionList) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ComponentVersionList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ComponentVersionSpec) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ComponentVersionSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ComponentVersionStatus) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ComponentVersionStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Discovery) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Discovery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DiscoveryList) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.DiscoveryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DiscoverySpec) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.DiscoverySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DiscoveryStatus) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.DiscoveryStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Filter) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Filter"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Registry) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Registry"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Release) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Release"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReleaseList) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ReleaseList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReleaseSpec) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ReleaseSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ReleaseStatus) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ReleaseStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ResourceAccess) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.ResourceAccess"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Webhook) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Webhook"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WebhookAuth) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.WebhookAuth"
}
