//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CatalogItem) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.CatalogItem"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CatalogItemList) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.CatalogItemList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CatalogItemSpec) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.CatalogItemSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CatalogItemStatus) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.CatalogItemStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CatalogItemVersionSpec) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.CatalogItemVersionSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Discovery) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Discovery"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DiscoveryList) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.DiscoveryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DiscoverySpec) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.DiscoverySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DiscoveryStatus) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.DiscoveryStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Registry) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Registry"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Webhook) OpenAPIModelName() string {
	return "cloud.opendefense.solar.v1alpha1.Webhook"
}
