//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 BWI GmbH and Artifact Conduit contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&CatalogItem{}, func(obj interface{}) { SetObjectDefaults_CatalogItem(obj.(*CatalogItem)) })
	scheme.AddTypeDefaultingFunc(&CatalogItemList{}, func(obj interface{}) { SetObjectDefaults_CatalogItemList(obj.(*CatalogItemList)) })
	return nil
}

func SetObjectDefaults_CatalogItem(in *CatalogItem) {
	SetDefaults_CatalogItemSpec(&in.Spec)
}

func SetObjectDefaults_CatalogItemList(in *CatalogItemList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_CatalogItem(a)
	}
}
