//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	solar "go.opendefense.cloud/solar/api/solar"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CatalogItem)(nil), (*solar.CatalogItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItem_To_solar_CatalogItem(a.(*CatalogItem), b.(*solar.CatalogItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItem)(nil), (*CatalogItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItem_To_v1alpha1_CatalogItem(a.(*solar.CatalogItem), b.(*CatalogItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemList)(nil), (*solar.CatalogItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(a.(*CatalogItemList), b.(*solar.CatalogItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemList)(nil), (*CatalogItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(a.(*solar.CatalogItemList), b.(*CatalogItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemSpec)(nil), (*solar.CatalogItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(a.(*CatalogItemSpec), b.(*solar.CatalogItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemSpec)(nil), (*CatalogItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(a.(*solar.CatalogItemSpec), b.(*CatalogItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemStatus)(nil), (*solar.CatalogItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(a.(*CatalogItemStatus), b.(*solar.CatalogItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemStatus)(nil), (*CatalogItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(a.(*solar.CatalogItemStatus), b.(*CatalogItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CatalogItemVersionSpec)(nil), (*solar.CatalogItemVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(a.(*CatalogItemVersionSpec), b.(*solar.CatalogItemVersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.CatalogItemVersionSpec)(nil), (*CatalogItemVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(a.(*solar.CatalogItemVersionSpec), b.(*CatalogItemVersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Cron)(nil), (*solar.Cron)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Cron_To_solar_Cron(a.(*Cron), b.(*solar.Cron), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.Cron)(nil), (*Cron)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_Cron_To_v1alpha1_Cron(a.(*solar.Cron), b.(*Cron), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Discovery)(nil), (*solar.Discovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Discovery_To_solar_Discovery(a.(*Discovery), b.(*solar.Discovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.Discovery)(nil), (*Discovery)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_Discovery_To_v1alpha1_Discovery(a.(*solar.Discovery), b.(*Discovery), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiscoveryList)(nil), (*solar.DiscoveryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiscoveryList_To_solar_DiscoveryList(a.(*DiscoveryList), b.(*solar.DiscoveryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.DiscoveryList)(nil), (*DiscoveryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_DiscoveryList_To_v1alpha1_DiscoveryList(a.(*solar.DiscoveryList), b.(*DiscoveryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiscoverySpec)(nil), (*solar.DiscoverySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiscoverySpec_To_solar_DiscoverySpec(a.(*DiscoverySpec), b.(*solar.DiscoverySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.DiscoverySpec)(nil), (*DiscoverySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_DiscoverySpec_To_v1alpha1_DiscoverySpec(a.(*solar.DiscoverySpec), b.(*DiscoverySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiscoveryStatus)(nil), (*solar.DiscoveryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiscoveryStatus_To_solar_DiscoveryStatus(a.(*DiscoveryStatus), b.(*solar.DiscoveryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.DiscoveryStatus)(nil), (*DiscoveryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_DiscoveryStatus_To_v1alpha1_DiscoveryStatus(a.(*solar.DiscoveryStatus), b.(*DiscoveryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Webhook)(nil), (*solar.Webhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Webhook_To_solar_Webhook(a.(*Webhook), b.(*solar.Webhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.Webhook)(nil), (*Webhook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_Webhook_To_v1alpha1_Webhook(a.(*solar.Webhook), b.(*Webhook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WebhookAuth)(nil), (*solar.WebhookAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WebhookAuth_To_solar_WebhookAuth(a.(*WebhookAuth), b.(*solar.WebhookAuth), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*solar.WebhookAuth)(nil), (*WebhookAuth)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_solar_WebhookAuth_To_v1alpha1_WebhookAuth(a.(*solar.WebhookAuth), b.(*WebhookAuth), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CatalogItem_To_solar_CatalogItem(in *CatalogItem, out *solar.CatalogItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CatalogItem_To_solar_CatalogItem is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItem_To_solar_CatalogItem(in *CatalogItem, out *solar.CatalogItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItem_To_solar_CatalogItem(in, out, s)
}

func autoConvert_solar_CatalogItem_To_v1alpha1_CatalogItem(in *solar.CatalogItem, out *CatalogItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_solar_CatalogItem_To_v1alpha1_CatalogItem is an autogenerated conversion function.
func Convert_solar_CatalogItem_To_v1alpha1_CatalogItem(in *solar.CatalogItem, out *CatalogItem, s conversion.Scope) error {
	return autoConvert_solar_CatalogItem_To_v1alpha1_CatalogItem(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(in *CatalogItemList, out *solar.CatalogItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]solar.CatalogItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_CatalogItemList_To_solar_CatalogItemList is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(in *CatalogItemList, out *solar.CatalogItemList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemList_To_solar_CatalogItemList(in, out, s)
}

func autoConvert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(in *solar.CatalogItemList, out *CatalogItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CatalogItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_solar_CatalogItemList_To_v1alpha1_CatalogItemList is an autogenerated conversion function.
func Convert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(in *solar.CatalogItemList, out *CatalogItemList, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemList_To_v1alpha1_CatalogItemList(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(in *CatalogItemSpec, out *solar.CatalogItemSpec, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Versions = *(*[]solar.CatalogItemVersionSpec)(unsafe.Pointer(&in.Versions))
	out.Provider = in.Provider
	out.CreationTime = in.CreationTime
	return nil
}

// Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(in *CatalogItemSpec, out *solar.CatalogItemSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemSpec_To_solar_CatalogItemSpec(in, out, s)
}

func autoConvert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(in *solar.CatalogItemSpec, out *CatalogItemSpec, s conversion.Scope) error {
	out.Repository = in.Repository
	out.Versions = *(*[]CatalogItemVersionSpec)(unsafe.Pointer(&in.Versions))
	out.Provider = in.Provider
	out.CreationTime = in.CreationTime
	return nil
}

// Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec is an autogenerated conversion function.
func Convert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(in *solar.CatalogItemSpec, out *CatalogItemSpec, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemSpec_To_v1alpha1_CatalogItemSpec(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(in *CatalogItemStatus, out *solar.CatalogItemStatus, s conversion.Scope) error {
	out.LastDiscoveredAt = (*v1.Time)(unsafe.Pointer(in.LastDiscoveredAt))
	return nil
}

// Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(in *CatalogItemStatus, out *solar.CatalogItemStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemStatus_To_solar_CatalogItemStatus(in, out, s)
}

func autoConvert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(in *solar.CatalogItemStatus, out *CatalogItemStatus, s conversion.Scope) error {
	out.LastDiscoveredAt = (*v1.Time)(unsafe.Pointer(in.LastDiscoveredAt))
	return nil
}

// Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus is an autogenerated conversion function.
func Convert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(in *solar.CatalogItemStatus, out *CatalogItemStatus, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemStatus_To_v1alpha1_CatalogItemStatus(in, out, s)
}

func autoConvert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(in *CatalogItemVersionSpec, out *solar.CatalogItemVersionSpec, s conversion.Scope) error {
	out.Version = in.Version
	out.Digest = in.Digest
	return nil
}

// Convert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec is an autogenerated conversion function.
func Convert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(in *CatalogItemVersionSpec, out *solar.CatalogItemVersionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CatalogItemVersionSpec_To_solar_CatalogItemVersionSpec(in, out, s)
}

func autoConvert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(in *solar.CatalogItemVersionSpec, out *CatalogItemVersionSpec, s conversion.Scope) error {
	out.Version = in.Version
	out.Digest = in.Digest
	return nil
}

// Convert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec is an autogenerated conversion function.
func Convert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(in *solar.CatalogItemVersionSpec, out *CatalogItemVersionSpec, s conversion.Scope) error {
	return autoConvert_solar_CatalogItemVersionSpec_To_v1alpha1_CatalogItemVersionSpec(in, out, s)
}

func autoConvert_v1alpha1_Cron_To_solar_Cron(in *Cron, out *solar.Cron, s conversion.Scope) error {
	out.Timezone = in.Timezone
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Schedules = *(*[]string)(unsafe.Pointer(&in.Schedules))
	return nil
}

// Convert_v1alpha1_Cron_To_solar_Cron is an autogenerated conversion function.
func Convert_v1alpha1_Cron_To_solar_Cron(in *Cron, out *solar.Cron, s conversion.Scope) error {
	return autoConvert_v1alpha1_Cron_To_solar_Cron(in, out, s)
}

func autoConvert_solar_Cron_To_v1alpha1_Cron(in *solar.Cron, out *Cron, s conversion.Scope) error {
	out.Timezone = in.Timezone
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.Schedules = *(*[]string)(unsafe.Pointer(&in.Schedules))
	return nil
}

// Convert_solar_Cron_To_v1alpha1_Cron is an autogenerated conversion function.
func Convert_solar_Cron_To_v1alpha1_Cron(in *solar.Cron, out *Cron, s conversion.Scope) error {
	return autoConvert_solar_Cron_To_v1alpha1_Cron(in, out, s)
}

func autoConvert_v1alpha1_Discovery_To_solar_Discovery(in *Discovery, out *solar.Discovery, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DiscoverySpec_To_solar_DiscoverySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DiscoveryStatus_To_solar_DiscoveryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Discovery_To_solar_Discovery is an autogenerated conversion function.
func Convert_v1alpha1_Discovery_To_solar_Discovery(in *Discovery, out *solar.Discovery, s conversion.Scope) error {
	return autoConvert_v1alpha1_Discovery_To_solar_Discovery(in, out, s)
}

func autoConvert_solar_Discovery_To_v1alpha1_Discovery(in *solar.Discovery, out *Discovery, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_solar_DiscoverySpec_To_v1alpha1_DiscoverySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_solar_DiscoveryStatus_To_v1alpha1_DiscoveryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_solar_Discovery_To_v1alpha1_Discovery is an autogenerated conversion function.
func Convert_solar_Discovery_To_v1alpha1_Discovery(in *solar.Discovery, out *Discovery, s conversion.Scope) error {
	return autoConvert_solar_Discovery_To_v1alpha1_Discovery(in, out, s)
}

func autoConvert_v1alpha1_DiscoveryList_To_solar_DiscoveryList(in *DiscoveryList, out *solar.DiscoveryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]solar.Discovery)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DiscoveryList_To_solar_DiscoveryList is an autogenerated conversion function.
func Convert_v1alpha1_DiscoveryList_To_solar_DiscoveryList(in *DiscoveryList, out *solar.DiscoveryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiscoveryList_To_solar_DiscoveryList(in, out, s)
}

func autoConvert_solar_DiscoveryList_To_v1alpha1_DiscoveryList(in *solar.DiscoveryList, out *DiscoveryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Discovery)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_solar_DiscoveryList_To_v1alpha1_DiscoveryList is an autogenerated conversion function.
func Convert_solar_DiscoveryList_To_v1alpha1_DiscoveryList(in *solar.DiscoveryList, out *DiscoveryList, s conversion.Scope) error {
	return autoConvert_solar_DiscoveryList_To_v1alpha1_DiscoveryList(in, out, s)
}

func autoConvert_v1alpha1_DiscoverySpec_To_solar_DiscoverySpec(in *DiscoverySpec, out *solar.DiscoverySpec, s conversion.Scope) error {
	out.RegistryURL = in.RegistryURL
	out.DiscoverySecretRef = in.DiscoverySecretRef
	out.ReleaseSecretRef = in.ReleaseSecretRef
	out.Cron = (*solar.Cron)(unsafe.Pointer(in.Cron))
	out.DisableStartupDiscovery = in.DisableStartupDiscovery
	out.Webhook = (*solar.Webhook)(unsafe.Pointer(in.Webhook))
	return nil
}

// Convert_v1alpha1_DiscoverySpec_To_solar_DiscoverySpec is an autogenerated conversion function.
func Convert_v1alpha1_DiscoverySpec_To_solar_DiscoverySpec(in *DiscoverySpec, out *solar.DiscoverySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiscoverySpec_To_solar_DiscoverySpec(in, out, s)
}

func autoConvert_solar_DiscoverySpec_To_v1alpha1_DiscoverySpec(in *solar.DiscoverySpec, out *DiscoverySpec, s conversion.Scope) error {
	out.RegistryURL = in.RegistryURL
	out.DiscoverySecretRef = in.DiscoverySecretRef
	out.ReleaseSecretRef = in.ReleaseSecretRef
	out.Cron = (*Cron)(unsafe.Pointer(in.Cron))
	out.DisableStartupDiscovery = in.DisableStartupDiscovery
	out.Webhook = (*Webhook)(unsafe.Pointer(in.Webhook))
	return nil
}

// Convert_solar_DiscoverySpec_To_v1alpha1_DiscoverySpec is an autogenerated conversion function.
func Convert_solar_DiscoverySpec_To_v1alpha1_DiscoverySpec(in *solar.DiscoverySpec, out *DiscoverySpec, s conversion.Scope) error {
	return autoConvert_solar_DiscoverySpec_To_v1alpha1_DiscoverySpec(in, out, s)
}

func autoConvert_v1alpha1_DiscoveryStatus_To_solar_DiscoveryStatus(in *DiscoveryStatus, out *solar.DiscoveryStatus, s conversion.Scope) error {
	out.DiscoveryVersion = in.DiscoveryVersion
	return nil
}

// Convert_v1alpha1_DiscoveryStatus_To_solar_DiscoveryStatus is an autogenerated conversion function.
func Convert_v1alpha1_DiscoveryStatus_To_solar_DiscoveryStatus(in *DiscoveryStatus, out *solar.DiscoveryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiscoveryStatus_To_solar_DiscoveryStatus(in, out, s)
}

func autoConvert_solar_DiscoveryStatus_To_v1alpha1_DiscoveryStatus(in *solar.DiscoveryStatus, out *DiscoveryStatus, s conversion.Scope) error {
	out.DiscoveryVersion = in.DiscoveryVersion
	return nil
}

// Convert_solar_DiscoveryStatus_To_v1alpha1_DiscoveryStatus is an autogenerated conversion function.
func Convert_solar_DiscoveryStatus_To_v1alpha1_DiscoveryStatus(in *solar.DiscoveryStatus, out *DiscoveryStatus, s conversion.Scope) error {
	return autoConvert_solar_DiscoveryStatus_To_v1alpha1_DiscoveryStatus(in, out, s)
}

func autoConvert_v1alpha1_Webhook_To_solar_Webhook(in *Webhook, out *solar.Webhook, s conversion.Scope) error {
	out.Flavor = in.Flavor
	out.Path = in.Path
	out.Auth = *(*[]solar.WebhookAuth)(unsafe.Pointer(&in.Auth))
	return nil
}

// Convert_v1alpha1_Webhook_To_solar_Webhook is an autogenerated conversion function.
func Convert_v1alpha1_Webhook_To_solar_Webhook(in *Webhook, out *solar.Webhook, s conversion.Scope) error {
	return autoConvert_v1alpha1_Webhook_To_solar_Webhook(in, out, s)
}

func autoConvert_solar_Webhook_To_v1alpha1_Webhook(in *solar.Webhook, out *Webhook, s conversion.Scope) error {
	out.Flavor = in.Flavor
	out.Path = in.Path
	out.Auth = *(*[]WebhookAuth)(unsafe.Pointer(&in.Auth))
	return nil
}

// Convert_solar_Webhook_To_v1alpha1_Webhook is an autogenerated conversion function.
func Convert_solar_Webhook_To_v1alpha1_Webhook(in *solar.Webhook, out *Webhook, s conversion.Scope) error {
	return autoConvert_solar_Webhook_To_v1alpha1_Webhook(in, out, s)
}

func autoConvert_v1alpha1_WebhookAuth_To_solar_WebhookAuth(in *WebhookAuth, out *solar.WebhookAuth, s conversion.Scope) error {
	out.Type = in.Type
	out.SecretRef = in.SecretRef
	return nil
}

// Convert_v1alpha1_WebhookAuth_To_solar_WebhookAuth is an autogenerated conversion function.
func Convert_v1alpha1_WebhookAuth_To_solar_WebhookAuth(in *WebhookAuth, out *solar.WebhookAuth, s conversion.Scope) error {
	return autoConvert_v1alpha1_WebhookAuth_To_solar_WebhookAuth(in, out, s)
}

func autoConvert_solar_WebhookAuth_To_v1alpha1_WebhookAuth(in *solar.WebhookAuth, out *WebhookAuth, s conversion.Scope) error {
	out.Type = in.Type
	out.SecretRef = in.SecretRef
	return nil
}

// Convert_solar_WebhookAuth_To_v1alpha1_WebhookAuth is an autogenerated conversion function.
func Convert_solar_WebhookAuth_To_v1alpha1_WebhookAuth(in *solar.WebhookAuth, out *WebhookAuth, s conversion.Scope) error {
	return autoConvert_solar_WebhookAuth_To_v1alpha1_WebhookAuth(in, out, s)
}
