{{- $name := printf "%s-%s" $.Release.Name $.Values.component.name }}

{{- if gt (len $name) 53 }}
  {{- $sha := $name | sha256sum | trunc 10 }}
  {{- $name = printf "%s-%s" ($name | trunc 42) $sha }}
{{- end }}

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  interval: 4m
  url: oci://{{ .Values.helm.repository }}
  # FIXME: replace hardcoded secret with outcome of #165
  secretRef:
    name: regcred
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: {{ .Values.helm.tag }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: {{ $name }}
  releaseName: {{ $name }}
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    << .Values | toYaml | nindent 4 >>
