{{- $name := printf "%s-%s" $.Release.Name $.Values.component.name }}
{{- if gt (len $name) 53 }}
  {{- $sha := $name | sha256sum | trunc 10 }}
  {{- $name = printf "%s-%s" ($name | trunc 42) $sha }}
{{- end }}

{{- $epName := .Values.entrypoint.resourceName }}
{{- if not (hasKey .Values.resources $epName) }}
  {{- fail (printf "entrypoint resource %q not found in .Values.resources" $epName) }}
{{- end }}
{{- $resource := index .Values.resources $epName }}
{{- if not $resource.repository }}
  {{- fail (printf "resource %q has empty repository" $epName) }}
{{- end }}
{{- if not $resource.tag }}
  {{- fail (printf "resource %q has empty tag" $epName) }}
{{- end }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  interval: 4m
  url: oci://{{ $resource.repository }}
  {{- if $resource.insecure }}
  insecure: true
  {{- end }}
  # FIXME: replace hardcoded secret with outcome of #165
  secretRef:
    name: regcred
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    {{- if hasPrefix "@" $resource.tag }}
    digest: "{{ trimPrefix "@" $resource.tag }}"
    {{- else }}
    tag: "{{ $resource.tag }}"
    {{- end }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: {{ $name }}
  releaseName: {{ $name }}
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    << .Values | toYaml | nindent 4 >>
