// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/solar/client-go/clientset/versioned/typed/solar/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSolarV1alpha1 struct {
	*testing.Fake
}

func (c *FakeSolarV1alpha1) CatalogItems(namespace string) v1alpha1.CatalogItemInterface {
	return newFakeCatalogItems(c, namespace)
}

func (c *FakeSolarV1alpha1) Discoveries(namespace string) v1alpha1.DiscoveryInterface {
	return newFakeDiscoveries(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSolarV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
