// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	solarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	typedsolarv1alpha1 "go.opendefense.cloud/solar/client-go/clientset/versioned/typed/solar/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDiscoveries implements DiscoveryInterface
type fakeDiscoveries struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Discovery, *v1alpha1.DiscoveryList, *solarv1alpha1.DiscoveryApplyConfiguration]
	Fake *FakeSolarV1alpha1
}

func newFakeDiscoveries(fake *FakeSolarV1alpha1, namespace string) typedsolarv1alpha1.DiscoveryInterface {
	return &fakeDiscoveries{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Discovery, *v1alpha1.DiscoveryList, *solarv1alpha1.DiscoveryApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("discoveries"),
			v1alpha1.SchemeGroupVersion.WithKind("Discovery"),
			func() *v1alpha1.Discovery { return &v1alpha1.Discovery{} },
			func() *v1alpha1.DiscoveryList { return &v1alpha1.DiscoveryList{} },
			func(dst, src *v1alpha1.DiscoveryList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DiscoveryList) []*v1alpha1.Discovery { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.DiscoveryList, items []*v1alpha1.Discovery) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
