// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	solarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	typedsolarv1alpha1 "go.opendefense.cloud/solar/client-go/clientset/versioned/typed/solar/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHydratedTargets implements HydratedTargetInterface
type fakeHydratedTargets struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.HydratedTarget, *v1alpha1.HydratedTargetList, *solarv1alpha1.HydratedTargetApplyConfiguration]
	Fake *FakeSolarV1alpha1
}

func newFakeHydratedTargets(fake *FakeSolarV1alpha1, namespace string) typedsolarv1alpha1.HydratedTargetInterface {
	return &fakeHydratedTargets{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.HydratedTarget, *v1alpha1.HydratedTargetList, *solarv1alpha1.HydratedTargetApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("hydratedtargets"),
			v1alpha1.SchemeGroupVersion.WithKind("HydratedTarget"),
			func() *v1alpha1.HydratedTarget { return &v1alpha1.HydratedTarget{} },
			func() *v1alpha1.HydratedTargetList { return &v1alpha1.HydratedTargetList{} },
			func(dst, src *v1alpha1.HydratedTargetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.HydratedTargetList) []*v1alpha1.HydratedTarget {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.HydratedTargetList, items []*v1alpha1.HydratedTarget) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
