// Copyright BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	solarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	typedsolarv1alpha1 "go.opendefense.cloud/solar/client-go/clientset/versioned/typed/solar/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTargetReports implements TargetReportInterface
type fakeTargetReports struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.TargetReport, *v1alpha1.TargetReportList, *solarv1alpha1.TargetReportApplyConfiguration]
	Fake *FakeSolarV1alpha1
}

func newFakeTargetReports(fake *FakeSolarV1alpha1, namespace string) typedsolarv1alpha1.TargetReportInterface {
	return &fakeTargetReports{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.TargetReport, *v1alpha1.TargetReportList, *solarv1alpha1.TargetReportApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("targetreports"),
			v1alpha1.SchemeGroupVersion.WithKind("TargetReport"),
			func() *v1alpha1.TargetReport { return &v1alpha1.TargetReport{} },
			func() *v1alpha1.TargetReportList { return &v1alpha1.TargetReportList{} },
			func(dst, src *v1alpha1.TargetReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.TargetReportList) []*v1alpha1.TargetReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.TargetReportList, items []*v1alpha1.TargetReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
