// Copyright 2026 BWI GmbH and Solution Arsenal contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.opendefense.cloud/solar/api/solar/v1alpha1"
	solarv1alpha1 "go.opendefense.cloud/solar/client-go/applyconfigurations/solar/v1alpha1"
	typedsolarv1alpha1 "go.opendefense.cloud/solar/client-go/clientset/versioned/typed/solar/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRenderArtifacts implements RenderArtifactInterface
type fakeRenderArtifacts struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.RenderArtifact, *v1alpha1.RenderArtifactList, *solarv1alpha1.RenderArtifactApplyConfiguration]
	Fake *FakeSolarV1alpha1
}

func newFakeRenderArtifacts(fake *FakeSolarV1alpha1, namespace string) typedsolarv1alpha1.RenderArtifactInterface {
	return &fakeRenderArtifacts{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.RenderArtifact, *v1alpha1.RenderArtifactList, *solarv1alpha1.RenderArtifactApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("renderartifacts"),
			v1alpha1.SchemeGroupVersion.WithKind("RenderArtifact"),
			func() *v1alpha1.RenderArtifact { return &v1alpha1.RenderArtifact{} },
			func() *v1alpha1.RenderArtifactList { return &v1alpha1.RenderArtifactList{} },
			func(dst, src *v1alpha1.RenderArtifactList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.RenderArtifactList) []*v1alpha1.RenderArtifact {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.RenderArtifactList, items []*v1alpha1.RenderArtifact) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
