name: Conventional Commits
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
permissions:
  pull-requests: read
jobs:
  conventional-commits:
    uses: opendefensecloud/dev-kit/.github/workflows/conventional-commits.yml@c9fbc95b84be3c9acdb02656091eca21dfee8501 # v3.0.0
