name: Golang CI
permissions:
  contents: read

on:
  push:
    branches: [main, develop]
    paths:
      - "**/*.go"
      - ".github/workflows/golang.yaml"
      - "devenv.nix"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [main, develop]
    paths:
      - "**/*.go"
      - ".github/workflows/golang.yaml"
      - "devenv.nix"
      - "go.mod"
      - "go.sum"

env:
  GO_MODULE: https://github.com/opendefensecloud/solution-arsenal

jobs:
  lint:
    runs-on: arc-scale-set
    outputs:
      go-version: ${{ steps.get-go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - name: get-go-version
        id: get-go-version
        run: |
          GO_VERSION="$(grep -oP 'languages.go.version = "\K[^"]+' devenv.nix)"
          if [ -z "$GO_VERSION" ]; then
            echo "::error::Failed to extract Go version from devenv.nix"
            exit 1
          fi
          echo "version=$GO_VERSION" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ steps.get-go-version.outputs.version }}
      - name: lint-license-and-shell
        run: |
          make lint-no-golangci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9

  test:
    needs: lint
    runs-on: arc-scale-set
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ needs.lint.outputs.go-version }}
      - name: test
        run: |
          make ocm
          make ocm-transfer
          make test
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.2.0
        with:
          infile: solar.coverprofile
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.7
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
