name: Label issues
on:
  issues:
    types: [opened, reopened]
permissions:
  contents: read
jobs:
  label:
    permissions:
      issues: write
    uses: opendefensecloud/dev-kit/.github/workflows/issues-add-labels.yaml@c9fbc95b84be3c9acdb02656091eca21dfee8501 # v3.0.0
