name: Add issues to project
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:
  contents: read
jobs:
  add-to-project:
    permissions: {}
    uses: opendefensecloud/dev-kit/.github/workflows/issues-add-to-project.yml@c9fbc95b84be3c9acdb02656091eca21dfee8501 # v3.0.0
    secrets:
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
