name: OSV-Scanner
on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "12 12 * * 1"
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  osv-scanner:
    permissions:
      actions: read
      security-events: write
      contents: read
    uses: opendefensecloud/dev-kit/.github/workflows/osv-scanner.yml@c9fbc95b84be3c9acdb02656091eca21dfee8501 # v3.0.0
    with:
      scan-args: |-
        --include-git-root
        --config ./.osv-scanner.toml
        -r
        ./
