name: Update Action Pins
on:
  pull_request:
permissions:
  contents: read
jobs:
  update-action-pins:
    uses: opendefensecloud/dev-kit/.github/workflows/update-action-pins.yml@c9fbc95b84be3c9acdb02656091eca21dfee8501 # v3.0.0
